/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const AddressScalarFieldEnumSchema = z.enum(["id", "street", "city", "state", "postalCode", "country", "createdAt", "updatedAt"])
