/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const CategoryScalarFieldEnumSchema = z.enum(["id", "name", "slug", "parentId", "createdAt", "updatedAt"])
