/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const CustomerScalarFieldEnumSchema = z.enum(["id", "name", "email", "phoneNumber", "createdAt", "updatedAt", "userId", "cartId"])
