/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const ImageSizeSchema = z.enum(["THUMB", "MEDIUM", "LARGE", "ORIGINAL"])
