/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const MediaTypeSchema = z.enum(["Image", "Video", "Audio", "Document", "File"])
