/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const MediaScalarFieldEnumSchema = z.enum(["id", "type", "key", "imageSize", "fileName", "mimeType", "fileSize", "duration", "width", "height", "isStale", "createdAt", "updatedAt"])
