/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const OrderScalarFieldEnumSchema = z.enum(["id", "customerId", "shipmentId", "status", "createdAt", "updatedAt"])
