/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const OrderStatusSchema = z.enum(["PENDING", "PAID", "SHIPPED", "DELIVERED", "CANCELLED", "RETURNED"])
