/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const PaymentStatusSchema = z.enum(["PENDING", "PAID", "REFUNDED", "FAILED", "CANCELLED"])
