/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const PaymentScalarFieldEnumSchema = z.enum(["id", "orderId", "amount", "method", "status", "createdAt", "updatedAt"])
