/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const ProductScalarFieldEnumSchema = z.enum(["id", "name", "description", "price", "stock", "imageUrl", "createdAt", "updatedAt"])
