/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const ProductVariantGalleryMediaScalarFieldEnumSchema = z.enum(["id", "isPrimary", "sortOrder", "productVariantId", "mediaId"])
