/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const ShippingContactInformationScalarFieldEnumSchema = z.enum(["id", "firstName", "surname", "phoneNumber", "createdAt", "updatedAt"])
