/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const ShippingAddressScalarFieldEnumSchema = z.enum(["id", "shippingContactInformationId", "addressId", "customerId", "createdAt", "updatedAt"])
