/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const TokenScalarFieldEnumSchema = z.enum(["id", "token", "type", "userId", "createdAt", "expiresAt", "revoked", "ip", "userAgent"])
