/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const VendorScalarFieldEnumSchema = z.enum(["id", "name", "slug", "description", "ownerId", "status", "createdAt", "updatedAt"])
