/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const VendorUserScalarFieldEnumSchema = z.enum(["id", "vendorId", "userId", "role", "createdAt"])
