/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';

export const VendorUserRoleSchema = z.enum(["OWNER", "MANAGER", "STAFF", "VIEWER"])
