/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    street: z.string(),
    city: z.string(),
    state: z.string(),
    postalCode: z.string(),
    country: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    shippingAddress: z.record(z.unknown()).optional(),
}
);

/**
 * `Address` schema excluding foreign keys and relations.
 */
export const AddressScalarSchema = baseSchema;


/**
 * `Address` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const AddressSchema = AddressScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const AddressPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const AddressPrismaUpdateSchema = z.object({
    id: z.string(),
    street: z.string(),
    city: z.string(),
    state: z.string(),
    postalCode: z.string(),
    country: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Address` schema for create operations excluding foreign keys and relations.
 */
export const AddressCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Address` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const AddressCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Address` schema for update operations excluding foreign keys and relations.
 */
export const AddressUpdateScalarSchema = baseSchema.partial();


/**
 * `Address` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const AddressUpdateSchema = AddressUpdateScalarSchema;

