/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    duration: z.number(),
}
).strict();
const relationSchema = z.object({
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    id: z.string(),
}
);

/**
 * `Audio` schema excluding foreign keys and relations.
 */
export const AudioScalarSchema = baseSchema;


/**
 * `Audio` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const AudioSchema = AudioScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const AudioPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const AudioPrismaUpdateSchema = z.object({
    id: z.string(),
    duration: z.union([z.number(), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `Audio` schema for create operations excluding foreign keys and relations.
 */
export const AudioCreateScalarSchema = baseSchema;


/**
 * `Audio` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const AudioCreateSchema = AudioCreateScalarSchema.merge(fkSchema);


/**
 * `Audio` schema for update operations excluding foreign keys and relations.
 */
export const AudioUpdateScalarSchema = baseSchema.partial();


/**
 * `Audio` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const AudioUpdateSchema = AudioUpdateScalarSchema.merge(fkSchema.partial());

