/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { MediaTypeSchema } from '../enums/MediaType.schema';
const baseSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    mediaType: MediaTypeSchema,
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.number(),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    duration: z.number(),
}
).strict();
const relationSchema = z.object({
    product: z.record(z.unknown()).optional(),
}
);

/**
 * `Audio` schema excluding foreign keys and relations.
 */
export const AudioScalarSchema = baseSchema;


/**
 * `Audio` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const AudioSchema = AudioScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const AudioPrismaCreateSchema = baseSchema.omit({ mediaType: true }).partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const AudioPrismaUpdateSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.union([z.number(), z.record(z.unknown())]),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    duration: z.union([z.number(), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `Audio` schema for create operations excluding foreign keys and relations.
 */
export const AudioCreateScalarSchema = baseSchema.omit({ mediaType: true }).partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Audio` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const AudioCreateSchema = baseSchema.omit({ mediaType: true }).partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Audio` schema for update operations excluding foreign keys and relations.
 */
export const AudioUpdateScalarSchema = baseSchema.omit({ mediaType: true }).partial();


/**
 * `Audio` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const AudioUpdateSchema = AudioUpdateScalarSchema;

