/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    quantity: z.number(),
}
).strict();
const relationSchema = z.object({
    cart: z.record(z.unknown()),
    productVariant: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    cartId: z.string(),
    productVariantId: z.string(),
}
);

/**
 * `CartItem` schema excluding foreign keys and relations.
 */
export const CartItemScalarSchema = baseSchema;


/**
 * `CartItem` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CartItemSchema = CartItemScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CartItemPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CartItemPrismaUpdateSchema = z.object({
    id: z.string(),
    quantity: z.union([z.number(), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `CartItem` schema for create operations excluding foreign keys and relations.
 */
export const CartItemCreateScalarSchema = baseSchema.partial({
    id: true
});


/**
 * `CartItem` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CartItemCreateSchema = CartItemCreateScalarSchema.merge(fkSchema);


/**
 * `CartItem` schema for update operations excluding foreign keys and relations.
 */
export const CartItemUpdateScalarSchema = baseSchema.partial();


/**
 * `CartItem` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CartItemUpdateSchema = CartItemUpdateScalarSchema.merge(fkSchema.partial());

