/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    customer: z.record(z.unknown()),
    cartItems: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    customerId: z.string(),
}
);

/**
 * `Cart` schema excluding foreign keys and relations.
 */
export const CartScalarSchema = baseSchema;


/**
 * `Cart` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CartSchema = CartScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CartPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CartPrismaUpdateSchema = z.object({
    id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Cart` schema for create operations excluding foreign keys and relations.
 */
export const CartCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Cart` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CartCreateSchema = CartCreateScalarSchema.merge(fkSchema);


/**
 * `Cart` schema for update operations excluding foreign keys and relations.
 */
export const CartUpdateScalarSchema = baseSchema.partial();


/**
 * `Cart` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CartUpdateSchema = CartUpdateScalarSchema.merge(fkSchema.partial());

