/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    name: z.string(),
    slug: z.string(),
    parentId: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    products: z.array(z.unknown()).optional(),
}
);

/**
 * `Category` schema excluding foreign keys and relations.
 */
export const CategoryScalarSchema = baseSchema;


/**
 * `Category` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CategorySchema = CategoryScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CategoryPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CategoryPrismaUpdateSchema = z.object({
    id: z.string(),
    name: z.string(),
    slug: z.string(),
    parentId: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Category` schema for create operations excluding foreign keys and relations.
 */
export const CategoryCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Category` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CategoryCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Category` schema for update operations excluding foreign keys and relations.
 */
export const CategoryUpdateScalarSchema = baseSchema.partial();


/**
 * `Category` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CategoryUpdateSchema = CategoryUpdateScalarSchema;

