/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    name: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    addresses: z.array(z.unknown()).optional(),
    orders: z.array(z.unknown()).optional(),
    cart: z.record(z.unknown()).optional(),
    user: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    userId: z.string(),
}
);

/**
 * `Customer` schema excluding foreign keys and relations.
 */
export const CustomerScalarSchema = baseSchema;


/**
 * `Customer` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const CustomerSchema = CustomerScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const CustomerPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const CustomerPrismaUpdateSchema = z.object({
    id: z.string(),
    name: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Customer` schema for create operations excluding foreign keys and relations.
 */
export const CustomerCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Customer` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const CustomerCreateSchema = CustomerCreateScalarSchema.merge(fkSchema);


/**
 * `Customer` schema for update operations excluding foreign keys and relations.
 */
export const CustomerUpdateScalarSchema = baseSchema.partial();


/**
 * `Customer` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const CustomerUpdateSchema = CustomerUpdateScalarSchema.merge(fkSchema.partial());

