/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    length: z.number(),
    width: z.number(),
    height: z.number(),
    unit: z.string().default("cm"),
}
).strict();
export const DimensionsSchema = baseSchema;
