/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
}
).strict();
const relationSchema = z.object({
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    id: z.string(),
}
);

/**
 * `Document` schema excluding foreign keys and relations.
 */
export const DocumentScalarSchema = baseSchema;


/**
 * `Document` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const DocumentSchema = DocumentScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const DocumentPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const DocumentPrismaUpdateSchema = z.object({
    id: z.string()
}).partial().passthrough();


/**
 * `Document` schema for create operations excluding foreign keys and relations.
 */
export const DocumentCreateScalarSchema = baseSchema;


/**
 * `Document` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const DocumentCreateSchema = DocumentCreateScalarSchema.merge(fkSchema);


/**
 * `Document` schema for update operations excluding foreign keys and relations.
 */
export const DocumentUpdateScalarSchema = baseSchema.partial();


/**
 * `Document` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const DocumentUpdateSchema = DocumentUpdateScalarSchema.merge(fkSchema.partial());

