/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
}
).strict();
const relationSchema = z.object({
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    id: z.string(),
}
);

/**
 * `File` schema excluding foreign keys and relations.
 */
export const FileScalarSchema = baseSchema;


/**
 * `File` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const FileSchema = FileScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const FilePrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const FilePrismaUpdateSchema = z.object({
    id: z.string()
}).partial().passthrough();


/**
 * `File` schema for create operations excluding foreign keys and relations.
 */
export const FileCreateScalarSchema = baseSchema;


/**
 * `File` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const FileCreateSchema = FileCreateScalarSchema.merge(fkSchema);


/**
 * `File` schema for update operations excluding foreign keys and relations.
 */
export const FileUpdateScalarSchema = baseSchema.partial();


/**
 * `File` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const FileUpdateSchema = FileUpdateScalarSchema.merge(fkSchema.partial());

