/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { MediaTypeSchema } from '../enums/MediaType.schema';
import { ImageSizeSchema } from '../enums/ImageSize.schema';
const baseSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    mediaType: MediaTypeSchema,
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.number(),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    width: z.number(),
    height: z.number(),
    imageSize: ImageSizeSchema,
}
).strict();
const relationSchema = z.object({
    product: z.record(z.unknown()).optional(),
    parent: z.record(z.unknown()).optional(),
    children: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    parentId: z.string().nullish(),
}
);

/**
 * `Image` schema excluding foreign keys and relations.
 */
export const ImageScalarSchema = baseSchema;


/**
 * `Image` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ImageSchema = ImageScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ImagePrismaCreateSchema = baseSchema.omit({ mediaType: true }).partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ImagePrismaUpdateSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.union([z.number(), z.record(z.unknown())]),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
    width: z.union([z.number(), z.record(z.unknown())]),
    height: z.union([z.number(), z.record(z.unknown())]),
    imageSize: ImageSizeSchema
}).partial().passthrough();


/**
 * `Image` schema for create operations excluding foreign keys and relations.
 */
export const ImageCreateScalarSchema = baseSchema.omit({ mediaType: true }).partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Image` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ImageCreateSchema = ImageCreateScalarSchema.merge(fkSchema);


/**
 * `Image` schema for update operations excluding foreign keys and relations.
 */
export const ImageUpdateScalarSchema = baseSchema.omit({ mediaType: true }).partial();


/**
 * `Image` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ImageUpdateSchema = ImageUpdateScalarSchema.merge(fkSchema.partial());

