/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ImageSizeSchema } from '../enums/ImageSize.schema';
const baseSchema = z.object({
    id: z.string(),
    width: z.number(),
    height: z.number(),
    imageSize: ImageSizeSchema,
}
).strict();
const relationSchema = z.object({
    parent: z.record(z.unknown()).optional(),
    children: z.array(z.unknown()).optional(),
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    id: z.string(),
    parentId: z.string().nullish(),
}
);

/**
 * `Image` schema excluding foreign keys and relations.
 */
export const ImageScalarSchema = baseSchema;


/**
 * `Image` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ImageSchema = ImageScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ImagePrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ImagePrismaUpdateSchema = z.object({
    id: z.string(),
    width: z.union([z.number(), z.record(z.unknown())]),
    height: z.union([z.number(), z.record(z.unknown())]),
    imageSize: ImageSizeSchema
}).partial().passthrough();


/**
 * `Image` schema for create operations excluding foreign keys and relations.
 */
export const ImageCreateScalarSchema = baseSchema;


/**
 * `Image` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ImageCreateSchema = ImageCreateScalarSchema.merge(fkSchema);


/**
 * `Image` schema for update operations excluding foreign keys and relations.
 */
export const ImageUpdateScalarSchema = baseSchema.partial();


/**
 * `Image` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ImageUpdateSchema = ImageUpdateScalarSchema.merge(fkSchema.partial());

