/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.number(),
    level: z.string(),
    requestData: z.any().nullish(),
    timestamp: z.coerce.date().default(() => new Date()),
    message: z.string(),
}
).strict();

/**
 * `Log` schema excluding foreign keys and relations.
 */
export const LogScalarSchema = baseSchema;


/**
 * `Log` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const LogSchema = LogScalarSchema;


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const LogPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const LogPrismaUpdateSchema = z.object({
    id: z.union([z.number(), z.record(z.unknown())]),
    level: z.string(),
    requestData: z.any().nullish(),
    timestamp: z.coerce.date().default(() => new Date()),
    message: z.string()
}).partial().passthrough();


/**
 * `Log` schema for create operations excluding foreign keys and relations.
 */
export const LogCreateScalarSchema = baseSchema.partial({
    id: true, timestamp: true
});


/**
 * `Log` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const LogCreateSchema = baseSchema.partial({
    id: true, timestamp: true
});


/**
 * `Log` schema for update operations excluding foreign keys and relations.
 */
export const LogUpdateScalarSchema = baseSchema.partial();


/**
 * `Log` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const LogUpdateSchema = LogUpdateScalarSchema;

