/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { MediaType } from '../../../generated/client';
import { MediaTypeSchema } from '../enums/MediaType.schema';
import { ImageSizeSchema } from '../enums/ImageSize.schema';
const baseSchema = z.object({
    id: z.string(),
    type: MediaTypeSchema,
    key: z.string(),
    imageSize: ImageSizeSchema.nullish(),
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.number(),
    duration: z.number().nullish(),
    width: z.number().nullish(),
    height: z.number().nullish(),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();

/**
* Schema refinement function for applying `@@validate` rules.
*/
export function refineMedia<T, D extends z.ZodTypeDef>(schema: z.ZodType<T, D, T>) {
    return schema.refine((value: any) => ((value?.imageSize !== null && value?.imageSize !== undefined) && ((value?.type) !== undefined ? ((value?.type == MediaType.IMAGE)) : true)), { message: "imageSize can only be set for images", });
}


/**
 * `Media` schema excluding foreign keys and relations.
 */
export const MediaScalarSchema = baseSchema;


/**
 * `Media` schema prior to calling `.refine()` for extensibility.
 */
export const MediaWithoutRefineSchema = MediaScalarSchema;


/**
 * `Media` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const MediaSchema = refineMedia(MediaWithoutRefineSchema);


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const MediaPrismaCreateSchema = refineMedia(baseSchema.partial().passthrough());


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const MediaPrismaUpdateSchema = z.object({
    id: z.string(),
    type: MediaTypeSchema,
    key: z.string(),
    imageSize: ImageSizeSchema.nullish(),
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.union([z.number(), z.record(z.unknown())]),
    duration: z.union([z.number().nullish(), z.record(z.unknown())]),
    width: z.union([z.number().nullish(), z.record(z.unknown())]),
    height: z.union([z.number().nullish(), z.record(z.unknown())]),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Media` schema for create operations excluding foreign keys and relations.
 */
export const MediaCreateScalarSchema = baseSchema.partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Media` schema for create operations prior to calling `.refine()` for extensibility.
 */
export const MediaCreateWithoutRefineSchema = baseSchema.partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Media` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const MediaCreateSchema = refineMedia(MediaCreateWithoutRefineSchema);


/**
 * `Media` schema for update operations excluding foreign keys and relations.
 */
export const MediaUpdateScalarSchema = baseSchema.partial();


/**
 * `Media` schema for update operations prior to calling `.refine()` for extensibility.
 */
export const MediaUpdateWithoutRefineSchema = MediaUpdateScalarSchema;


/**
 * `Media` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const MediaUpdateSchema = refineMedia(MediaUpdateWithoutRefineSchema);

