/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { MediaTypeSchema } from '../enums/MediaType.schema';
const baseSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    mediaType: MediaTypeSchema,
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.number(),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    image: z.record(z.unknown()).optional(),
    video: z.record(z.unknown()).optional(),
    audio: z.record(z.unknown()).optional(),
    document: z.record(z.unknown()).optional(),
    file: z.record(z.unknown()).optional(),
    productVariantGalleryMedia: z.record(z.unknown()).optional(),
    productVariantAttachment: z.record(z.unknown()).optional(),
}
);

/**
 * `Media` schema excluding foreign keys and relations.
 */
export const MediaScalarSchema = baseSchema;


/**
 * `Media` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const MediaSchema = MediaScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const MediaPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const MediaPrismaUpdateSchema = z.object({
    id: z.string(),
    bucketKey: z.string(),
    mediaType: MediaTypeSchema,
    fileName: z.string(),
    mimeType: z.string(),
    fileSize: z.union([z.number(), z.record(z.unknown())]),
    isStale: z.boolean().default(true),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Media` schema for create operations excluding foreign keys and relations.
 */
export const MediaCreateScalarSchema = baseSchema.partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Media` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const MediaCreateSchema = baseSchema.partial({
    id: true, isStale: true, createdAt: true, updatedAt: true
});


/**
 * `Media` schema for update operations excluding foreign keys and relations.
 */
export const MediaUpdateScalarSchema = baseSchema.partial();


/**
 * `Media` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const MediaUpdateSchema = MediaUpdateScalarSchema;

