/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { OrderStatusSchema } from '../enums/OrderStatus.schema';
const baseSchema = z.object({
    id: z.string(),
    status: OrderStatusSchema,
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    customer: z.record(z.unknown()),
    orderItems: z.array(z.unknown()).optional(),
    payment: z.record(z.unknown()).optional(),
    shipment: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    customerId: z.string(),
    shipmentId: z.string(),
}
);

/**
 * `Order` schema excluding foreign keys and relations.
 */
export const OrderScalarSchema = baseSchema;


/**
 * `Order` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const OrderSchema = OrderScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const OrderPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const OrderPrismaUpdateSchema = z.object({
    id: z.string(),
    status: OrderStatusSchema,
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Order` schema for create operations excluding foreign keys and relations.
 */
export const OrderCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Order` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const OrderCreateSchema = OrderCreateScalarSchema.merge(fkSchema);


/**
 * `Order` schema for update operations excluding foreign keys and relations.
 */
export const OrderUpdateScalarSchema = baseSchema.partial();


/**
 * `Order` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const OrderUpdateSchema = OrderUpdateScalarSchema.merge(fkSchema.partial());

