/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
}
).strict();
const relationSchema = z.object({
    productVariant: z.record(z.unknown()),
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    productVariantId: z.string(),
    mediaId: z.string(),
}
);

/**
 * `ProductVariantAttachment` schema excluding foreign keys and relations.
 */
export const ProductVariantAttachmentScalarSchema = baseSchema;


/**
 * `ProductVariantAttachment` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ProductVariantAttachmentSchema = ProductVariantAttachmentScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ProductVariantAttachmentPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ProductVariantAttachmentPrismaUpdateSchema = z.object({
    id: z.string()
}).partial().passthrough();


/**
 * `ProductVariantAttachment` schema for create operations excluding foreign keys and relations.
 */
export const ProductVariantAttachmentCreateScalarSchema = baseSchema.partial({
    id: true
});


/**
 * `ProductVariantAttachment` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantAttachmentCreateSchema = ProductVariantAttachmentCreateScalarSchema.merge(fkSchema);


/**
 * `ProductVariantAttachment` schema for update operations excluding foreign keys and relations.
 */
export const ProductVariantAttachmentUpdateScalarSchema = baseSchema.partial();


/**
 * `ProductVariantAttachment` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantAttachmentUpdateSchema = ProductVariantAttachmentUpdateScalarSchema.merge(fkSchema.partial());

