/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    isPrimary: z.boolean().default(false),
    sortOrder: z.number().default(0),
}
).strict();
const relationSchema = z.object({
    productVariant: z.record(z.unknown()),
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    productVariantId: z.string(),
    mediaId: z.string(),
}
);

/**
 * `ProductVariantGalleryMedia` schema excluding foreign keys and relations.
 */
export const ProductVariantGalleryMediaScalarSchema = baseSchema;


/**
 * `ProductVariantGalleryMedia` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ProductVariantGalleryMediaSchema = ProductVariantGalleryMediaScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ProductVariantGalleryMediaPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ProductVariantGalleryMediaPrismaUpdateSchema = z.object({
    id: z.string(),
    isPrimary: z.boolean().default(false),
    sortOrder: z.union([z.number().default(0), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `ProductVariantGalleryMedia` schema for create operations excluding foreign keys and relations.
 */
export const ProductVariantGalleryMediaCreateScalarSchema = baseSchema.partial({
    id: true, isPrimary: true, sortOrder: true
});


/**
 * `ProductVariantGalleryMedia` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantGalleryMediaCreateSchema = ProductVariantGalleryMediaCreateScalarSchema.merge(fkSchema);


/**
 * `ProductVariantGalleryMedia` schema for update operations excluding foreign keys and relations.
 */
export const ProductVariantGalleryMediaUpdateScalarSchema = baseSchema.partial();


/**
 * `ProductVariantGalleryMedia` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantGalleryMediaUpdateSchema = ProductVariantGalleryMediaUpdateScalarSchema.merge(fkSchema.partial());

