/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    isPrimary: z.boolean().default(false),
    sortOrder: z.number().default(0),
}
).strict();
const relationSchema = z.object({
    productVariant: z.record(z.unknown()),
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    productVariantId: z.string(),
    mediaId: z.string(),
}
);

/**
 * `ProductVariantMedia` schema excluding foreign keys and relations.
 */
export const ProductVariantMediaScalarSchema = baseSchema;


/**
 * `ProductVariantMedia` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ProductVariantMediaSchema = ProductVariantMediaScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ProductVariantMediaPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ProductVariantMediaPrismaUpdateSchema = z.object({
    id: z.string(),
    isPrimary: z.boolean().default(false),
    sortOrder: z.union([z.number().default(0), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `ProductVariantMedia` schema for create operations excluding foreign keys and relations.
 */
export const ProductVariantMediaCreateScalarSchema = baseSchema.partial({
    id: true, isPrimary: true, sortOrder: true
});


/**
 * `ProductVariantMedia` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantMediaCreateSchema = ProductVariantMediaCreateScalarSchema.merge(fkSchema);


/**
 * `ProductVariantMedia` schema for update operations excluding foreign keys and relations.
 */
export const ProductVariantMediaUpdateScalarSchema = baseSchema.partial();


/**
 * `ProductVariantMedia` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ProductVariantMediaUpdateSchema = ProductVariantMediaUpdateScalarSchema.merge(fkSchema.partial());

