/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    price: z.number(),
    stock: z.number(),
    imageUrl: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    orderItems: z.array(z.unknown()).optional(),
    cartItems: z.array(z.unknown()).optional(),
}
);

/**
 * `Product` schema excluding foreign keys and relations.
 */
export const ProductScalarSchema = baseSchema;


/**
 * `Product` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ProductSchema = ProductScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ProductPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ProductPrismaUpdateSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    price: z.union([z.number(), z.record(z.unknown())]),
    stock: z.union([z.number(), z.record(z.unknown())]),
    imageUrl: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Product` schema for create operations excluding foreign keys and relations.
 */
export const ProductCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Product` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ProductCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Product` schema for update operations excluding foreign keys and relations.
 */
export const ProductUpdateScalarSchema = baseSchema.partial();


/**
 * `Product` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ProductUpdateSchema = ProductUpdateScalarSchema;

