/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    rating: z.number(),
    review: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    product: z.record(z.unknown()),
    user: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    productId: z.string(),
    userId: z.string(),
}
);

/**
 * `Rating` schema excluding foreign keys and relations.
 */
export const RatingScalarSchema = baseSchema;


/**
 * `Rating` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const RatingSchema = RatingScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const RatingPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const RatingPrismaUpdateSchema = z.object({
    id: z.string(),
    rating: z.union([z.number(), z.record(z.unknown())]),
    review: z.string().nullish(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `Rating` schema for create operations excluding foreign keys and relations.
 */
export const RatingCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `Rating` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const RatingCreateSchema = RatingCreateScalarSchema.merge(fkSchema);


/**
 * `Rating` schema for update operations excluding foreign keys and relations.
 */
export const RatingUpdateScalarSchema = baseSchema.partial();


/**
 * `Rating` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const RatingUpdateSchema = RatingUpdateScalarSchema.merge(fkSchema.partial());

