/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    firstName: z.string(),
    surname: z.string(),
    phoneNumber: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    shippingAddress: z.record(z.unknown()).optional(),
}
);

/**
 * `ShippingContactInformation` schema excluding foreign keys and relations.
 */
export const ShippingContactInformationScalarSchema = baseSchema;


/**
 * `ShippingContactInformation` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ShippingContactInformationSchema = ShippingContactInformationScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ShippingContactInformationPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ShippingContactInformationPrismaUpdateSchema = z.object({
    id: z.string(),
    firstName: z.string(),
    surname: z.string(),
    phoneNumber: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `ShippingContactInformation` schema for create operations excluding foreign keys and relations.
 */
export const ShippingContactInformationCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `ShippingContactInformation` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingContactInformationCreateSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `ShippingContactInformation` schema for update operations excluding foreign keys and relations.
 */
export const ShippingContactInformationUpdateScalarSchema = baseSchema.partial();


/**
 * `ShippingContactInformation` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingContactInformationUpdateSchema = ShippingContactInformationUpdateScalarSchema;

