/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    shippingContactInformation: z.record(z.unknown()),
    address: z.record(z.unknown()),
    customer: z.record(z.unknown()),
    shipments: z.array(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    shippingContactInformationId: z.string(),
    addressId: z.string(),
    customerId: z.string(),
}
);

/**
 * `ShippingAddress` schema excluding foreign keys and relations.
 */
export const ShippingAddressScalarSchema = baseSchema;


/**
 * `ShippingAddress` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ShippingAddressSchema = ShippingAddressScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ShippingAddressPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ShippingAddressPrismaUpdateSchema = z.object({
    id: z.string(),
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `ShippingAddress` schema for create operations excluding foreign keys and relations.
 */
export const ShippingAddressCreateScalarSchema = baseSchema.partial({
    id: true, createdAt: true, updatedAt: true
});


/**
 * `ShippingAddress` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingAddressCreateSchema = ShippingAddressCreateScalarSchema.merge(fkSchema);


/**
 * `ShippingAddress` schema for update operations excluding foreign keys and relations.
 */
export const ShippingAddressUpdateScalarSchema = baseSchema.partial();


/**
 * `ShippingAddress` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingAddressUpdateSchema = ShippingAddressUpdateScalarSchema.merge(fkSchema.partial());

