/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    comment: z.string().nullish(),
    trackingNumber: z.string().nullish(),
}
).strict();
const relationSchema = z.object({
    shippingMethod: z.record(z.unknown()),
    shippingAddress: z.record(z.unknown()).optional(),
    order: z.record(z.unknown()).optional(),
}
);
const fkSchema = z.object({
    shippingMethodId: z.string(),
    shippingAddressId: z.string().nullish(),
}
);

/**
 * `Shipment` schema excluding foreign keys and relations.
 */
export const ShipmentScalarSchema = baseSchema;


/**
 * `Shipment` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ShipmentSchema = ShipmentScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ShipmentPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ShipmentPrismaUpdateSchema = z.object({
    id: z.string(),
    comment: z.string().nullish(),
    trackingNumber: z.string().nullish()
}).partial().passthrough();


/**
 * `Shipment` schema for create operations excluding foreign keys and relations.
 */
export const ShipmentCreateScalarSchema = baseSchema.partial({
    id: true
});


/**
 * `Shipment` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ShipmentCreateSchema = ShipmentCreateScalarSchema.merge(fkSchema);


/**
 * `Shipment` schema for update operations excluding foreign keys and relations.
 */
export const ShipmentUpdateScalarSchema = baseSchema.partial();


/**
 * `Shipment` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ShipmentUpdateSchema = ShipmentUpdateScalarSchema.merge(fkSchema.partial());

