/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { ShippingTypeSchema } from '../enums/ShippingType.schema';
import { DecimalSchema } from '../common';
import { Decimal } from 'decimal.js';
const baseSchema = z.object({
    id: z.string(),
    name: z.string(),
    type: ShippingTypeSchema,
    isActive: z.boolean().default(true),
    flatPrice: DecimalSchema,
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date(),
}
).strict();
const relationSchema = z.object({
    shipments: z.array(z.unknown()).optional(),
}
);

/**
 * `ShippingMethod` schema excluding foreign keys and relations.
 */
export const ShippingMethodScalarSchema = baseSchema;


/**
 * `ShippingMethod` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const ShippingMethodSchema = ShippingMethodScalarSchema.merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const ShippingMethodPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const ShippingMethodPrismaUpdateSchema = z.object({
    id: z.string(),
    name: z.string(),
    type: ShippingTypeSchema,
    isActive: z.boolean().default(true),
    flatPrice: DecimalSchema,
    createdAt: z.coerce.date().default(() => new Date()),
    updatedAt: z.coerce.date()
}).partial().passthrough();


/**
 * `ShippingMethod` schema for create operations excluding foreign keys and relations.
 */
export const ShippingMethodCreateScalarSchema = baseSchema.partial({
    id: true, isActive: true, createdAt: true, updatedAt: true
});


/**
 * `ShippingMethod` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingMethodCreateSchema = baseSchema.partial({
    id: true, isActive: true, createdAt: true, updatedAt: true
});


/**
 * `ShippingMethod` schema for update operations excluding foreign keys and relations.
 */
export const ShippingMethodUpdateScalarSchema = baseSchema.partial();


/**
 * `ShippingMethod` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const ShippingMethodUpdateSchema = ShippingMethodUpdateScalarSchema;

