/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
import { VendorUserRole } from '../../models';
import { VendorUserRoleSchema } from '../enums/VendorUserRole.schema';
const baseSchema = z.object({
    id: z.string(),
    role: VendorUserRoleSchema,
    createdAt: z.coerce.date().default(() => new Date()),
}
).strict();
const relationSchema = z.object({
    vendor: z.record(z.unknown()),
    user: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    vendorId: z.string(),
    userId: z.string(),
}
);

/**
 * `VendorUser` schema excluding foreign keys and relations.
 */
export const VendorUserScalarSchema = baseSchema;


/**
 * `VendorUser` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const VendorUserSchema = VendorUserScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const VendorUserPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const VendorUserPrismaUpdateSchema = z.object({
    id: z.string(),
    role: VendorUserRoleSchema,
    createdAt: z.coerce.date().default(() => new Date())
}).partial().passthrough();


/**
 * `VendorUser` schema for create operations excluding foreign keys and relations.
 */
export const VendorUserCreateScalarSchema = baseSchema.partial({
    id: true, role: true, createdAt: true
});


/**
 * `VendorUser` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const VendorUserCreateSchema = VendorUserCreateScalarSchema.merge(fkSchema);


/**
 * `VendorUser` schema for update operations excluding foreign keys and relations.
 */
export const VendorUserUpdateScalarSchema = baseSchema.partial();


/**
 * `VendorUser` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const VendorUserUpdateSchema = VendorUserUpdateScalarSchema.merge(fkSchema.partial());

