/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    id: z.string(),
    duration: z.number(),
}
).strict();
const relationSchema = z.object({
    media: z.record(z.unknown()),
}
);
const fkSchema = z.object({
    id: z.string(),
}
);

/**
 * `Video` schema excluding foreign keys and relations.
 */
export const VideoScalarSchema = baseSchema;


/**
 * `Video` schema including all fields (scalar, foreign key, and relations) and validations.
 */
export const VideoSchema = VideoScalarSchema.merge(fkSchema).merge(relationSchema.partial());


/**
 * Schema used for validating Prisma create input. For internal use only.
 * @private
 */
export const VideoPrismaCreateSchema = baseSchema.partial().passthrough();


/**
 * Schema used for validating Prisma update input. For internal use only.
 * @private
 */
export const VideoPrismaUpdateSchema = z.object({
    id: z.string(),
    duration: z.union([z.number(), z.record(z.unknown())])
}).partial().passthrough();


/**
 * `Video` schema for create operations excluding foreign keys and relations.
 */
export const VideoCreateScalarSchema = baseSchema;


/**
 * `Video` schema for create operations including scalar fields, foreign key fields, and validations.
 */
export const VideoCreateSchema = VideoCreateScalarSchema.merge(fkSchema);


/**
 * `Video` schema for update operations excluding foreign keys and relations.
 */
export const VideoUpdateScalarSchema = baseSchema.partial();


/**
 * `Video` schema for update operations including scalar fields, foreign key fields, and validations.
 */
export const VideoUpdateSchema = VideoUpdateScalarSchema.merge(fkSchema.partial());

