/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { z } from 'zod';
const baseSchema = z.object({
    value: z.number(),
    unit: z.string().default("g"),
}
).strict();
export const WeightSchema = baseSchema;
