FROM node:lts-slim as build

WORKDIR /app

COPY . .

RUN npm install --omit=dev

COPY --from=build /repo/apps/backend/dist ./apps/backend/dist
COPY --from=build /repo/apps/backend/src/integrations/express/routers ./apps/backend/src/integrations/express/routers
COPY --from=build /repo/libs/shared/dist ./libs/shared/dist
COPY --from=build /repo/libs/shared/src/prisma/generated/*.node ./libs/shared/dist/prisma/generated

RUN apt-get update -y && apt-get install -y openssl

ENV NODE_ENV=production

EXPOSE 3333

CMD ["npm", "run", "start:backend"]