/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export type Dimensions = {
    length: number;
    width: number;
    height: number;
    unit: string;
};
