/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import { type QueryContext, type CrudContract, type PermissionCheckerContext } from "@zenstackhq/runtime";
import { allFieldsEqual } from "@zenstackhq/runtime/validation";
import { type PolicyDef, type PermissionCheckerConstraint } from "@zenstackhq/runtime/enhancements/node";
import { MediaType } from "../generated/client";
import { ImageSize } from "../generated/client";
import { ProductStatus } from "../generated/client";
import { OrderStatus } from "../generated/client";
import { Role } from "../generated/client";
import { TokenType } from "../generated/client";
import { PaymentStatus } from "../generated/client";
import { PaymentMethod } from "../generated/client";

const policy: PolicyDef = {
    policy: {
        media: {
            modelLevel: {
                read: { guard: Media_read, },
                create: { guard: Media_create, inputChecker: Media_create_input, },
                update: { guard: Media_update, },
                postUpdate: { guard: Media_postUpdate, },
                delete: { guard: Media_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        image: {
            modelLevel: {
                read: { guard: Image_read, },
                create: { guard: Image_create, inputChecker: Image_create_input, },
                update: { guard: Image_update, },
                postUpdate: { guard: Image_postUpdate, },
                delete: { guard: Image_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        video: {
            modelLevel: {
                read: { guard: Video_read, },
                create: { guard: Video_create, inputChecker: Video_create_input, },
                update: { guard: Video_update, },
                postUpdate: { guard: Video_postUpdate, },
                delete: { guard: Video_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        audio: {
            modelLevel: {
                read: { guard: Audio_read, },
                create: { guard: Audio_create, inputChecker: Audio_create_input, },
                update: { guard: Audio_update, },
                postUpdate: { guard: Audio_postUpdate, },
                delete: { guard: Audio_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        document: {
            modelLevel: {
                read: { guard: Document_read, },
                create: { guard: Document_create, inputChecker: Document_create_input, },
                update: { guard: Document_update, },
                postUpdate: { guard: Document_postUpdate, },
                delete: { guard: Document_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        file: {
            modelLevel: {
                read: { guard: File_read, },
                create: { guard: File_create, inputChecker: File_create_input, },
                update: { guard: File_update, },
                postUpdate: { guard: File_postUpdate, },
                delete: { guard: File_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        product: {
            modelLevel: {
                read: { guard: Product_read, },
                create: { guard: Product_create, inputChecker: Product_create_input, },
                update: { guard: Product_update, },
                postUpdate: { guard: Product_postUpdate, },
                delete: { guard: Product_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        productVariant: {
            modelLevel: {
                read: { guard: ProductVariant_read, },
                create: { guard: ProductVariant_create, inputChecker: ProductVariant_create_input, },
                update: { guard: ProductVariant_update, },
                postUpdate: { guard: ProductVariant_postUpdate, },
                delete: { guard: ProductVariant_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        productVariantMedia: {
            modelLevel: {
                read: { guard: ProductVariantMedia_read, },
                create: { guard: ProductVariantMedia_create, inputChecker: ProductVariantMedia_create_input, },
                update: { guard: ProductVariantMedia_update, },
                postUpdate: { guard: ProductVariantMedia_postUpdate, },
                delete: { guard: ProductVariantMedia_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        order: {
            modelLevel: {
                read: { guard: Order_read, },
                create: { guard: Order_create, inputChecker: Order_create_input, },
                update: { guard: Order_update, },
                postUpdate: { guard: Order_postUpdate, },
                delete: { guard: Order_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        orderItem: {
            modelLevel: {
                read: { guard: OrderItem_read, },
                create: { guard: OrderItem_create, inputChecker: OrderItem_create_input, },
                update: { guard: OrderItem_update, },
                postUpdate: { guard: OrderItem_postUpdate, },
                delete: { guard: OrderItem_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        customer: {
            modelLevel: {
                read: { guard: Customer_read, },
                create: { guard: Customer_create, inputChecker: Customer_create_input, },
                update: { guard: Customer_update, },
                postUpdate: { guard: Customer_postUpdate, },
                delete: { guard: Customer_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        address: {
            modelLevel: {
                read: { guard: Address_read, },
                create: { guard: Address_create, inputChecker: Address_create_input, },
                update: { guard: Address_update, },
                postUpdate: { guard: Address_postUpdate, },
                delete: { guard: Address_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        cart: {
            modelLevel: {
                read: { guard: Cart_read, },
                create: { guard: Cart_create, inputChecker: Cart_create_input, },
                update: { guard: Cart_update, },
                postUpdate: { guard: Cart_postUpdate, },
                delete: { guard: Cart_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        cartItem: {
            modelLevel: {
                read: { guard: CartItem_read, },
                create: { guard: CartItem_create, inputChecker: CartItem_create_input, },
                update: { guard: CartItem_update, },
                postUpdate: { guard: CartItem_postUpdate, },
                delete: { guard: CartItem_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        user: {
            modelLevel: {
                read: { guard: User_read, },
                create: { guard: User_create, inputChecker: User_create_input, },
                update: { guard: User_update, },
                postUpdate: { guard: User_postUpdate, },
                delete: { guard: User_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        token: {
            modelLevel: {
                read: { guard: Token_read, },
                create: { guard: Token_create, inputChecker: Token_create_input, },
                update: { guard: Token_update, },
                postUpdate: { guard: Token_postUpdate, },
                delete: { guard: Token_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        rating: {
            modelLevel: {
                read: { guard: Rating_read, },
                create: { guard: Rating_create, inputChecker: Rating_create_input, },
                update: { guard: Rating_update, },
                postUpdate: { guard: Rating_postUpdate, },
                delete: { guard: Rating_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        payment: {
            modelLevel: {
                read: { guard: Payment_read, },
                create: { guard: Payment_create, inputChecker: Payment_create_input, },
                update: { guard: Payment_update, },
                postUpdate: { guard: Payment_postUpdate, },
                delete: { guard: Payment_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        category: {
            modelLevel: {
                read: { guard: Category_read, },
                create: { guard: Category_create, inputChecker: Category_create_input, },
                update: { guard: Category_update, },
                postUpdate: { guard: Category_postUpdate, },
                delete: { guard: Category_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        tag: {
            modelLevel: {
                read: { guard: Tag_read, },
                create: { guard: Tag_create, inputChecker: Tag_create_input, },
                update: { guard: Tag_update, },
                postUpdate: { guard: Tag_postUpdate, },
                delete: { guard: Tag_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
        log: {
            modelLevel: {
                read: { guard: Log_read, },
                create: { guard: Log_create, inputChecker: Log_create_input, },
                update: { guard: Log_update, },
                postUpdate: { guard: Log_postUpdate, },
                delete: { guard: Log_delete, }
            },
            fieldLevel: {
                read:
                {

                },
                update:
                {

                },
            },

        },
    },
    validation: {
        media: { hasValidation: false },
        image: { hasValidation: false },
        video: { hasValidation: false },
        audio: { hasValidation: false },
        document: { hasValidation: false },
        file: { hasValidation: false },
        product: { hasValidation: false },
        productVariant: { hasValidation: true },
        productVariantMedia: { hasValidation: false },
        order: { hasValidation: false },
        orderItem: { hasValidation: false },
        customer: { hasValidation: false },
        address: { hasValidation: false },
        cart: { hasValidation: false },
        cartItem: { hasValidation: false },
        user: { hasValidation: false },
        token: { hasValidation: false },
        rating: { hasValidation: false },
        payment: { hasValidation: false },
        category: { hasValidation: false },
        tag: { hasValidation: false },
        log: { hasValidation: false },
    },

};

function Media_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Media_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Media_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Media_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Media_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Media_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Media_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Media_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Media_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Media_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Media_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Image_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Image_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Image_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Image_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Image_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Image_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Image_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Video_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Video_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Video_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Video_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Video_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Video_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Video_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Video_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Video_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Video_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Video_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Audio_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Audio_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Audio_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Audio_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Audio_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Audio_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Audio_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Audio_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Audio_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Audio_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Audio_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Document_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Document_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Document_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Document_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Document_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Document_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Document_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function File_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function File_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function File_create_input(input: any, context: QueryContext): boolean {
    return true
}

function File_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function File_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function File_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_File_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Product_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Product_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Product_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Product_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Product_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Product_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Product_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Product_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Product_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Product_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Product_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function ProductVariant_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariant_read(input: any, context: QueryContext): any {
    return false;
}

function ProductVariant_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariant_create(input: any, context: QueryContext): any {
    return false;
}

function ProductVariant_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function ProductVariant_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariant_update(input: any, context: QueryContext): any {
    return false;
}

function ProductVariant_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ProductVariant_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ProductVariant_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariant_delete(input: any, context: QueryContext): any {
    return false;
}

function ProductVariantMedia_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariantMedia_read(input: any, context: QueryContext): any {
    return false;
}

function ProductVariantMedia_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariantMedia_create(input: any, context: QueryContext): any {
    return false;
}

function ProductVariantMedia_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function ProductVariantMedia_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariantMedia_update(input: any, context: QueryContext): any {
    return false;
}

function ProductVariantMedia_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_ProductVariantMedia_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function ProductVariantMedia_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_ProductVariantMedia_delete(input: any, context: QueryContext): any {
    return false;
}

function Order_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Order_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Order_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Order_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Order_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Order_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Order_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Order_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Order_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Order_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Order_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function OrderItem_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrderItem_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function OrderItem_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrderItem_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function OrderItem_create_input(input: any, context: QueryContext): boolean {
    return true
}

function OrderItem_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrderItem_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function OrderItem_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrderItem_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function OrderItem_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_OrderItem_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Customer_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Customer_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Customer_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Customer_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Customer_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Customer_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Customer_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Customer_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Customer_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Customer_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Customer_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Address_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Address_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Address_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Address_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Address_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Address_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Address_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Address_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Address_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Address_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Address_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Cart_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Cart_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Cart_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Cart_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Cart_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Cart_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Cart_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Cart_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Cart_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Cart_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Cart_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function CartItem_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CartItem_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function CartItem_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CartItem_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function CartItem_create_input(input: any, context: QueryContext): boolean {
    return true
}

function CartItem_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CartItem_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function CartItem_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CartItem_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function CartItem_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_CartItem_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function User_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function User_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function User_create_input(input: any, context: QueryContext): boolean {
    return true
}

function User_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function User_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function User_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_User_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Token_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Token_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Token_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Token_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Token_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Token_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Token_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Rating_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Rating_read(input: any, context: QueryContext): any {
    return false;
}

function Rating_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Rating_create(input: any, context: QueryContext): any {
    return false;
}

function Rating_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function Rating_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Rating_update(input: any, context: QueryContext): any {
    return false;
}

function Rating_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Rating_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Rating_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Rating_delete(input: any, context: QueryContext): any {
    return false;
}

function Payment_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Payment_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Payment_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Payment_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Payment_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Payment_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Payment_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Payment_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Payment_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Payment_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Payment_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Category_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Category_read(input: any, context: QueryContext): any {
    return false;
}

function Category_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Category_create(input: any, context: QueryContext): any {
    return false;
}

function Category_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function Category_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Category_update(input: any, context: QueryContext): any {
    return false;
}

function Category_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Category_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Category_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Category_delete(input: any, context: QueryContext): any {
    return false;
}

function Tag_read(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Tag_read(input: any, context: QueryContext): any {
    return false;
}

function Tag_create(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Tag_create(input: any, context: QueryContext): any {
    return false;
}

function Tag_create_input(input: any, context: QueryContext): boolean {
    return false;
}

function Tag_update(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Tag_update(input: any, context: QueryContext): any {
    return false;
}

function Tag_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Tag_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Tag_delete(context: QueryContext, db: CrudContract): any {
    return { OR: [] };
}

function $check_Tag_delete(input: any, context: QueryContext): any {
    return false;
}

function Log_read(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Log_read(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Log_create(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Log_create(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Log_create_input(input: any, context: QueryContext): boolean {
    return true
}

function Log_update(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Log_update(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}

function Log_postUpdate(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Log_postUpdate(input: any, context: QueryContext): any {
    return true;
}

function Log_delete(context: QueryContext, db: CrudContract): any {
    return { AND: [] };
}

function $check_Log_delete(input: any, context: QueryContext): any {
    if (true) { return true; }

    return false;
}
export default policy
