
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Media
 * const media = await prisma.media.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<ClientOptions extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions, Log = $Class.LogOptions<ClientOptions>, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<ClientOptions, Log, ExtArgs>
export { Prisma }



/**
 * Model Media
 * @@allow('all', true)
 * @@delegate(mediaType)
 */
export type Media = Prisma.MediaModel
/**
 * Model Image
 * @@allow('all', true)
 */
export type Image = Prisma.ImageModel
/**
 * Model Video
 * @@allow('all', true)
 */
export type Video = Prisma.VideoModel
/**
 * Model Audio
 * @@allow('all', true)
 */
export type Audio = Prisma.AudioModel
/**
 * Model Document
 * @@allow('all', true)
 */
export type Document = Prisma.DocumentModel
/**
 * Model File
 * @@allow('all', true)
 */
export type File = Prisma.FileModel
/**
 * Model Product
 * @@allow('all', true)
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model ProductVariantMedia
 * 
 */
export type ProductVariantMedia = Prisma.ProductVariantMediaModel
/**
 * Model Order
 * @@allow('all', true)
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * @@allow('all', true)
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Customer
 * @@allow('all', true)
 */
export type Customer = Prisma.CustomerModel
/**
 * Model Address
 * @@allow('all', true)
 */
export type Address = Prisma.AddressModel
/**
 * Model Cart
 * @@allow('all', true)
 */
export type Cart = Prisma.CartModel
/**
 * Model CartItem
 * @@allow('all', true)
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model User
 * @@allow('all', true)
 */
export type User = Prisma.UserModel
/**
 * Model Token
 * @@allow('all', true)
 */
export type Token = Prisma.TokenModel
/**
 * Model Rating
 * 
 */
export type Rating = Prisma.RatingModel
/**
 * Model Payment
 * @@allow('all', true)
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Tag
 * 
 */
export type Tag = Prisma.TagModel
/**
 * Model Log
 * @@allow('all', true)
 */
export type Log = Prisma.LogModel

export type MediaType = $Enums.MediaType
export const MediaType = $Enums.MediaType

export type ImageSize = $Enums.ImageSize
export const ImageSize = $Enums.ImageSize

export type ProductStatus = $Enums.ProductStatus
export const ProductStatus = $Enums.ProductStatus

export type OrderStatus = $Enums.OrderStatus
export const OrderStatus = $Enums.OrderStatus

export type Role = $Enums.Role
export const Role = $Enums.Role

export type TokenType = $Enums.TokenType
export const TokenType = $Enums.TokenType

export type PaymentStatus = $Enums.PaymentStatus
export const PaymentStatus = $Enums.PaymentStatus

export type PaymentMethod = $Enums.PaymentMethod
export const PaymentMethod = $Enums.PaymentMethod
