import $Types = runtime.Types;
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"
/**
 * Model Media
 * @
 * @allow ('all', true)
 */
export type MediaModel = runtime.Types.Result.DefaultSelection<Prisma.$MediaPayload>;
export type AggregateMedia = {
      _count: MediaCountAggregateOutputType | null
      _avg: MediaAvgAggregateOutputType | null
      _sum: MediaSumAggregateOutputType | null
      _min: MediaMinAggregateOutputType | null
      _max: MediaMaxAggregateOutputType | null
    };
export type MediaAvgAggregateOutputType = {
      fileSize: number | null
    };
export type MediaSumAggregateOutputType = {
      fileSize: number | null
    };
export type MediaMinAggregateOutputType = {
      id: string | null
      bucketKey: string | null
      mediaType: $Enums.MediaType | null
      fileName: string | null
      mimeType: string | null
      fileSize: number | null
      isStale: boolean | null
      createdAt: Date | null
      updatedAt: Date | null
    };
export type MediaMaxAggregateOutputType = {
      id: string | null
      bucketKey: string | null
      mediaType: $Enums.MediaType | null
      fileName: string | null
      mimeType: string | null
      fileSize: number | null
      isStale: boolean | null
      createdAt: Date | null
      updatedAt: Date | null
    };
export type MediaCountAggregateOutputType = {
      id: number
      bucketKey: number
      mediaType: number
      fileName: number
      mimeType: number
      fileSize: number
      isStale: number
      createdAt: number
      updatedAt: number
      _all: number
    };
export type MediaAvgAggregateInputType = {
      fileSize?: true
    };
export type MediaSumAggregateInputType = {
      fileSize?: true
    };
export type MediaMinAggregateInputType = {
      id?: true
      bucketKey?: true
      mediaType?: true
      fileName?: true
      mimeType?: true
      fileSize?: true
      isStale?: true
      createdAt?: true
      updatedAt?: true
    };
export type MediaMaxAggregateInputType = {
      id?: true
      bucketKey?: true
      mediaType?: true
      fileName?: true
      mimeType?: true
      fileSize?: true
      isStale?: true
      createdAt?: true
      updatedAt?: true
    };
export type MediaCountAggregateInputType = {
      id?: true
      bucketKey?: true
      mediaType?: true
      fileName?: true
      mimeType?: true
      fileSize?: true
      isStale?: true
      createdAt?: true
      updatedAt?: true
      _all?: true
    };
export type MediaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which Media to aggregate.
       */
      where?: Prisma.MediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of Media to fetch.
       */
      orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the start position
       */
      cursor?: Prisma.MediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` Media from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` Media.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Count returned Media
      **/
      _count?: true | MediaCountAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to average
      **/
      _avg?: MediaAvgAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to sum
      **/
      _sum?: MediaSumAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the minimum value
      **/
      _min?: MediaMinAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the maximum value
      **/
      _max?: MediaMaxAggregateInputType
    };
export type GetMediaAggregateType<T extends MediaAggregateArgs> = {
          [P in keyof T & keyof AggregateMedia]: P extends '_count' | 'count'
        ? T[P] extends true
          ? number
          : Prisma.GetScalarType<T[P], AggregateMedia[P]>
        : Prisma.GetScalarType<T[P], AggregateMedia[P]>
    };
export type MediaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      where?: Prisma.MediaWhereInput
      orderBy?: Prisma.MediaOrderByWithAggregationInput | Prisma.MediaOrderByWithAggregationInput[]
      by: Prisma.MediaScalarFieldEnum[] | Prisma.MediaScalarFieldEnum
      having?: Prisma.MediaScalarWhereWithAggregatesInput
      take?: number
      skip?: number
      _count?: MediaCountAggregateInputType | true
      _avg?: MediaAvgAggregateInputType
      _sum?: MediaSumAggregateInputType
      _min?: MediaMinAggregateInputType
      _max?: MediaMaxAggregateInputType
    };
export type MediaGroupByOutputType = {
      id: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale: boolean
      createdAt: Date
      updatedAt: Date
      _count: MediaCountAggregateOutputType | null
      _avg: MediaAvgAggregateOutputType | null
      _sum: MediaSumAggregateOutputType | null
      _min: MediaMinAggregateOutputType | null
      _max: MediaMaxAggregateOutputType | null
    };
type GetMediaGroupByPayload<T extends MediaGroupByArgs> = Prisma.PrismaPromise<
      Array<
        Prisma.PickEnumerable<MediaGroupByOutputType, T['by']> &
          {
            [P in ((keyof T) & (keyof MediaGroupByOutputType))]: P extends '_count'
              ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], MediaGroupByOutputType[P]>
              : Prisma.GetScalarType<T[P], MediaGroupByOutputType[P]>
          }
        >
      >;
export type MediaWhereInput = {
      AND?: Prisma.MediaWhereInput | Prisma.MediaWhereInput[]
      OR?: Prisma.MediaWhereInput[]
      NOT?: Prisma.MediaWhereInput | Prisma.MediaWhereInput[]
      id?: Prisma.StringFilter<"Media"> | string
      bucketKey?: Prisma.StringFilter<"Media"> | string
      mediaType?: Prisma.EnumMediaTypeFilter<"Media"> | $Enums.MediaType
      fileName?: Prisma.StringFilter<"Media"> | string
      mimeType?: Prisma.StringFilter<"Media"> | string
      fileSize?: Prisma.IntFilter<"Media"> | number
      isStale?: Prisma.BoolFilter<"Media"> | boolean
      createdAt?: Prisma.DateTimeFilter<"Media"> | Date | string
      updatedAt?: Prisma.DateTimeFilter<"Media"> | Date | string
      product?: Prisma.XOR<Prisma.ProductVariantMediaNullableScalarRelationFilter, Prisma.ProductVariantMediaWhereInput> | null
      image?: Prisma.XOR<Prisma.ImageNullableScalarRelationFilter, Prisma.ImageWhereInput> | null
      video?: Prisma.XOR<Prisma.VideoNullableScalarRelationFilter, Prisma.VideoWhereInput> | null
      audio?: Prisma.XOR<Prisma.AudioNullableScalarRelationFilter, Prisma.AudioWhereInput> | null
      document?: Prisma.XOR<Prisma.DocumentNullableScalarRelationFilter, Prisma.DocumentWhereInput> | null
      file?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
    };
export type MediaOrderByWithRelationInput = {
      id?: Prisma.SortOrder
      bucketKey?: Prisma.SortOrder
      mediaType?: Prisma.SortOrder
      fileName?: Prisma.SortOrder
      mimeType?: Prisma.SortOrder
      fileSize?: Prisma.SortOrder
      isStale?: Prisma.SortOrder
      createdAt?: Prisma.SortOrder
      updatedAt?: Prisma.SortOrder
      product?: Prisma.ProductVariantMediaOrderByWithRelationInput
      image?: Prisma.ImageOrderByWithRelationInput
      video?: Prisma.VideoOrderByWithRelationInput
      audio?: Prisma.AudioOrderByWithRelationInput
      document?: Prisma.DocumentOrderByWithRelationInput
      file?: Prisma.FileOrderByWithRelationInput
    };
export type MediaWhereUniqueInput = Prisma.AtLeast<{
      id?: string
      bucketKey?: string
      AND?: Prisma.MediaWhereInput | Prisma.MediaWhereInput[]
      OR?: Prisma.MediaWhereInput[]
      NOT?: Prisma.MediaWhereInput | Prisma.MediaWhereInput[]
      mediaType?: Prisma.EnumMediaTypeFilter<"Media"> | $Enums.MediaType
      fileName?: Prisma.StringFilter<"Media"> | string
      mimeType?: Prisma.StringFilter<"Media"> | string
      fileSize?: Prisma.IntFilter<"Media"> | number
      isStale?: Prisma.BoolFilter<"Media"> | boolean
      createdAt?: Prisma.DateTimeFilter<"Media"> | Date | string
      updatedAt?: Prisma.DateTimeFilter<"Media"> | Date | string
      product?: Prisma.XOR<Prisma.ProductVariantMediaNullableScalarRelationFilter, Prisma.ProductVariantMediaWhereInput> | null
      image?: Prisma.XOR<Prisma.ImageNullableScalarRelationFilter, Prisma.ImageWhereInput> | null
      video?: Prisma.XOR<Prisma.VideoNullableScalarRelationFilter, Prisma.VideoWhereInput> | null
      audio?: Prisma.XOR<Prisma.AudioNullableScalarRelationFilter, Prisma.AudioWhereInput> | null
      document?: Prisma.XOR<Prisma.DocumentNullableScalarRelationFilter, Prisma.DocumentWhereInput> | null
      file?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
    }, "id" | "bucketKey">;
export type MediaOrderByWithAggregationInput = {
      id?: Prisma.SortOrder
      bucketKey?: Prisma.SortOrder
      mediaType?: Prisma.SortOrder
      fileName?: Prisma.SortOrder
      mimeType?: Prisma.SortOrder
      fileSize?: Prisma.SortOrder
      isStale?: Prisma.SortOrder
      createdAt?: Prisma.SortOrder
      updatedAt?: Prisma.SortOrder
      _count?: Prisma.MediaCountOrderByAggregateInput
      _avg?: Prisma.MediaAvgOrderByAggregateInput
      _max?: Prisma.MediaMaxOrderByAggregateInput
      _min?: Prisma.MediaMinOrderByAggregateInput
      _sum?: Prisma.MediaSumOrderByAggregateInput
    };
export type MediaScalarWhereWithAggregatesInput = {
      AND?: Prisma.MediaScalarWhereWithAggregatesInput | Prisma.MediaScalarWhereWithAggregatesInput[]
      OR?: Prisma.MediaScalarWhereWithAggregatesInput[]
      NOT?: Prisma.MediaScalarWhereWithAggregatesInput | Prisma.MediaScalarWhereWithAggregatesInput[]
      id?: Prisma.StringWithAggregatesFilter<"Media"> | string
      bucketKey?: Prisma.StringWithAggregatesFilter<"Media"> | string
      mediaType?: Prisma.EnumMediaTypeWithAggregatesFilter<"Media"> | $Enums.MediaType
      fileName?: Prisma.StringWithAggregatesFilter<"Media"> | string
      mimeType?: Prisma.StringWithAggregatesFilter<"Media"> | string
      fileSize?: Prisma.IntWithAggregatesFilter<"Media"> | number
      isStale?: Prisma.BoolWithAggregatesFilter<"Media"> | boolean
      createdAt?: Prisma.DateTimeWithAggregatesFilter<"Media"> | Date | string
      updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Media"> | Date | string
    };
export type MediaCreateInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateManyInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
    };
export type MediaUpdateManyMutationInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    };
export type MediaUncheckedUpdateManyInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
    };
export type MediaCountOrderByAggregateInput = {
      id?: Prisma.SortOrder
      bucketKey?: Prisma.SortOrder
      mediaType?: Prisma.SortOrder
      fileName?: Prisma.SortOrder
      mimeType?: Prisma.SortOrder
      fileSize?: Prisma.SortOrder
      isStale?: Prisma.SortOrder
      createdAt?: Prisma.SortOrder
      updatedAt?: Prisma.SortOrder
    };
export type MediaAvgOrderByAggregateInput = {
      fileSize?: Prisma.SortOrder
    };
export type MediaMaxOrderByAggregateInput = {
      id?: Prisma.SortOrder
      bucketKey?: Prisma.SortOrder
      mediaType?: Prisma.SortOrder
      fileName?: Prisma.SortOrder
      mimeType?: Prisma.SortOrder
      fileSize?: Prisma.SortOrder
      isStale?: Prisma.SortOrder
      createdAt?: Prisma.SortOrder
      updatedAt?: Prisma.SortOrder
    };
export type MediaMinOrderByAggregateInput = {
      id?: Prisma.SortOrder
      bucketKey?: Prisma.SortOrder
      mediaType?: Prisma.SortOrder
      fileName?: Prisma.SortOrder
      mimeType?: Prisma.SortOrder
      fileSize?: Prisma.SortOrder
      isStale?: Prisma.SortOrder
      createdAt?: Prisma.SortOrder
      updatedAt?: Prisma.SortOrder
    };
export type MediaSumOrderByAggregateInput = {
      fileSize?: Prisma.SortOrder
    };
export type MediaScalarRelationFilter = {
      is?: Prisma.MediaWhereInput
      isNot?: Prisma.MediaWhereInput
    };
export type StringFieldUpdateOperationsInput = {
      set?: string
    };
export type EnumMediaTypeFieldUpdateOperationsInput = {
      set?: $Enums.MediaType
    };
export type IntFieldUpdateOperationsInput = {
      set?: number
      increment?: number
      decrement?: number
      multiply?: number
      divide?: number
    };
export type BoolFieldUpdateOperationsInput = {
      set?: boolean
    };
export type DateTimeFieldUpdateOperationsInput = {
      set?: Date | string
    };
export type MediaCreateNestedOneWithoutImageInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutImageInput, Prisma.MediaUncheckedCreateWithoutImageInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutImageInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutImageNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutImageInput, Prisma.MediaUncheckedCreateWithoutImageInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutImageInput
      upsert?: Prisma.MediaUpsertWithoutImageInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutImageInput, Prisma.MediaUpdateWithoutImageInput>, Prisma.MediaUncheckedUpdateWithoutImageInput>
    };
export type MediaCreateNestedOneWithoutVideoInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutVideoInput, Prisma.MediaUncheckedCreateWithoutVideoInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutVideoInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutVideoNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutVideoInput, Prisma.MediaUncheckedCreateWithoutVideoInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutVideoInput
      upsert?: Prisma.MediaUpsertWithoutVideoInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutVideoInput, Prisma.MediaUpdateWithoutVideoInput>, Prisma.MediaUncheckedUpdateWithoutVideoInput>
    };
export type MediaCreateNestedOneWithoutAudioInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutAudioInput, Prisma.MediaUncheckedCreateWithoutAudioInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutAudioInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutAudioNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutAudioInput, Prisma.MediaUncheckedCreateWithoutAudioInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutAudioInput
      upsert?: Prisma.MediaUpsertWithoutAudioInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutAudioInput, Prisma.MediaUpdateWithoutAudioInput>, Prisma.MediaUncheckedUpdateWithoutAudioInput>
    };
export type MediaCreateNestedOneWithoutDocumentInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutDocumentInput, Prisma.MediaUncheckedCreateWithoutDocumentInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutDocumentInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutDocumentNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutDocumentInput, Prisma.MediaUncheckedCreateWithoutDocumentInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutDocumentInput
      upsert?: Prisma.MediaUpsertWithoutDocumentInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutDocumentInput, Prisma.MediaUpdateWithoutDocumentInput>, Prisma.MediaUncheckedUpdateWithoutDocumentInput>
    };
export type MediaCreateNestedOneWithoutFileInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutFileInput, Prisma.MediaUncheckedCreateWithoutFileInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutFileInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutFileNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutFileInput, Prisma.MediaUncheckedCreateWithoutFileInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutFileInput
      upsert?: Prisma.MediaUpsertWithoutFileInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutFileInput, Prisma.MediaUpdateWithoutFileInput>, Prisma.MediaUncheckedUpdateWithoutFileInput>
    };
export type MediaCreateNestedOneWithoutProductInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutProductInput, Prisma.MediaUncheckedCreateWithoutProductInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutProductInput
      connect?: Prisma.MediaWhereUniqueInput
    };
export type MediaUpdateOneRequiredWithoutProductNestedInput = {
      create?: Prisma.XOR<Prisma.MediaCreateWithoutProductInput, Prisma.MediaUncheckedCreateWithoutProductInput>
      connectOrCreate?: Prisma.MediaCreateOrConnectWithoutProductInput
      upsert?: Prisma.MediaUpsertWithoutProductInput
      connect?: Prisma.MediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.MediaUpdateToOneWithWhereWithoutProductInput, Prisma.MediaUpdateWithoutProductInput>, Prisma.MediaUncheckedUpdateWithoutProductInput>
    };
export type MediaCreateWithoutImageInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutImageInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutImageInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutImageInput, Prisma.MediaUncheckedCreateWithoutImageInput>
    };
export type MediaUpsertWithoutImageInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutImageInput, Prisma.MediaUncheckedUpdateWithoutImageInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutImageInput, Prisma.MediaUncheckedCreateWithoutImageInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutImageInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutImageInput, Prisma.MediaUncheckedUpdateWithoutImageInput>
    };
export type MediaUpdateWithoutImageInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutImageInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateWithoutVideoInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutVideoInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutVideoInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutVideoInput, Prisma.MediaUncheckedCreateWithoutVideoInput>
    };
export type MediaUpsertWithoutVideoInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutVideoInput, Prisma.MediaUncheckedUpdateWithoutVideoInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutVideoInput, Prisma.MediaUncheckedCreateWithoutVideoInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutVideoInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutVideoInput, Prisma.MediaUncheckedUpdateWithoutVideoInput>
    };
export type MediaUpdateWithoutVideoInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutVideoInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateWithoutAudioInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutAudioInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutAudioInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutAudioInput, Prisma.MediaUncheckedCreateWithoutAudioInput>
    };
export type MediaUpsertWithoutAudioInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutAudioInput, Prisma.MediaUncheckedUpdateWithoutAudioInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutAudioInput, Prisma.MediaUncheckedCreateWithoutAudioInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutAudioInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutAudioInput, Prisma.MediaUncheckedUpdateWithoutAudioInput>
    };
export type MediaUpdateWithoutAudioInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutAudioInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateWithoutDocumentInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutDocumentInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutDocumentInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutDocumentInput, Prisma.MediaUncheckedCreateWithoutDocumentInput>
    };
export type MediaUpsertWithoutDocumentInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutDocumentInput, Prisma.MediaUncheckedUpdateWithoutDocumentInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutDocumentInput, Prisma.MediaUncheckedCreateWithoutDocumentInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutDocumentInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutDocumentInput, Prisma.MediaUncheckedUpdateWithoutDocumentInput>
    };
export type MediaUpdateWithoutDocumentInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutDocumentInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateWithoutFileInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutFileInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      product?: Prisma.ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutFileInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutFileInput, Prisma.MediaUncheckedCreateWithoutFileInput>
    };
export type MediaUpsertWithoutFileInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutFileInput, Prisma.MediaUncheckedUpdateWithoutFileInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutFileInput, Prisma.MediaUncheckedCreateWithoutFileInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutFileInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutFileInput, Prisma.MediaUncheckedUpdateWithoutFileInput>
    };
export type MediaUpdateWithoutFileInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutFileInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      product?: Prisma.ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaCreateWithoutProductInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      image?: Prisma.ImageCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentCreateNestedOneWithoutMediaInput
      file?: Prisma.FileCreateNestedOneWithoutMediaInput
    };
export type MediaUncheckedCreateWithoutProductInput = {
      id?: string
      bucketKey: string
      mediaType: $Enums.MediaType
      fileName: string
      mimeType: string
      fileSize: number
      isStale?: boolean
      createdAt?: Date | string
      updatedAt?: Date | string
      image?: Prisma.ImageUncheckedCreateNestedOneWithoutMediaInput
      video?: Prisma.VideoUncheckedCreateNestedOneWithoutMediaInput
      audio?: Prisma.AudioUncheckedCreateNestedOneWithoutMediaInput
      document?: Prisma.DocumentUncheckedCreateNestedOneWithoutMediaInput
      file?: Prisma.FileUncheckedCreateNestedOneWithoutMediaInput
    };
export type MediaCreateOrConnectWithoutProductInput = {
      where: Prisma.MediaWhereUniqueInput
      create: Prisma.XOR<Prisma.MediaCreateWithoutProductInput, Prisma.MediaUncheckedCreateWithoutProductInput>
    };
export type MediaUpsertWithoutProductInput = {
      update: Prisma.XOR<Prisma.MediaUpdateWithoutProductInput, Prisma.MediaUncheckedUpdateWithoutProductInput>
      create: Prisma.XOR<Prisma.MediaCreateWithoutProductInput, Prisma.MediaUncheckedCreateWithoutProductInput>
      where?: Prisma.MediaWhereInput
    };
export type MediaUpdateToOneWithWhereWithoutProductInput = {
      where?: Prisma.MediaWhereInput
      data: Prisma.XOR<Prisma.MediaUpdateWithoutProductInput, Prisma.MediaUncheckedUpdateWithoutProductInput>
    };
export type MediaUpdateWithoutProductInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      image?: Prisma.ImageUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUpdateOneWithoutMediaNestedInput
    };
export type MediaUncheckedUpdateWithoutProductInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      bucketKey?: Prisma.StringFieldUpdateOperationsInput | string
      mediaType?: Prisma.EnumMediaTypeFieldUpdateOperationsInput | $Enums.MediaType
      fileName?: Prisma.StringFieldUpdateOperationsInput | string
      mimeType?: Prisma.StringFieldUpdateOperationsInput | string
      fileSize?: Prisma.IntFieldUpdateOperationsInput | number
      isStale?: Prisma.BoolFieldUpdateOperationsInput | boolean
      createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
      image?: Prisma.ImageUncheckedUpdateOneWithoutMediaNestedInput
      video?: Prisma.VideoUncheckedUpdateOneWithoutMediaNestedInput
      audio?: Prisma.AudioUncheckedUpdateOneWithoutMediaNestedInput
      document?: Prisma.DocumentUncheckedUpdateOneWithoutMediaNestedInput
      file?: Prisma.FileUncheckedUpdateOneWithoutMediaNestedInput
    };
export type MediaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      bucketKey?: boolean
      mediaType?: boolean
      fileName?: boolean
      mimeType?: boolean
      fileSize?: boolean
      isStale?: boolean
      createdAt?: boolean
      updatedAt?: boolean
      product?: boolean | Prisma.Media$productArgs<ExtArgs>
      image?: boolean | Prisma.Media$imageArgs<ExtArgs>
      video?: boolean | Prisma.Media$videoArgs<ExtArgs>
      audio?: boolean | Prisma.Media$audioArgs<ExtArgs>
      document?: boolean | Prisma.Media$documentArgs<ExtArgs>
      file?: boolean | Prisma.Media$fileArgs<ExtArgs>
    }, ExtArgs["result"]["media"]>;
export type MediaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      bucketKey?: boolean
      mediaType?: boolean
      fileName?: boolean
      mimeType?: boolean
      fileSize?: boolean
      isStale?: boolean
      createdAt?: boolean
      updatedAt?: boolean
    }, ExtArgs["result"]["media"]>;
export type MediaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      bucketKey?: boolean
      mediaType?: boolean
      fileName?: boolean
      mimeType?: boolean
      fileSize?: boolean
      isStale?: boolean
      createdAt?: boolean
      updatedAt?: boolean
    }, ExtArgs["result"]["media"]>;
export type MediaSelectScalar = {
      id?: boolean
      bucketKey?: boolean
      mediaType?: boolean
      fileName?: boolean
      mimeType?: boolean
      fileSize?: boolean
      isStale?: boolean
      createdAt?: boolean
      updatedAt?: boolean
    };
export type MediaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "bucketKey" | "mediaType" | "fileName" | "mimeType" | "fileSize" | "isStale" | "createdAt" | "updatedAt", ExtArgs["result"]["media"]>;
export type MediaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      product?: boolean | Prisma.Media$productArgs<ExtArgs>
      image?: boolean | Prisma.Media$imageArgs<ExtArgs>
      video?: boolean | Prisma.Media$videoArgs<ExtArgs>
      audio?: boolean | Prisma.Media$audioArgs<ExtArgs>
      document?: boolean | Prisma.Media$documentArgs<ExtArgs>
      file?: boolean | Prisma.Media$fileArgs<ExtArgs>
    };
export type MediaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {};
export type MediaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {};
export type $MediaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      name: "Media"
      objects: {
        product: Prisma.$ProductVariantMediaPayload<ExtArgs> | null
        image: Prisma.$ImagePayload<ExtArgs> | null
        video: Prisma.$VideoPayload<ExtArgs> | null
        audio: Prisma.$AudioPayload<ExtArgs> | null
        document: Prisma.$DocumentPayload<ExtArgs> | null
        file: Prisma.$FilePayload<ExtArgs> | null
      }
      scalars: runtime.Types.Extensions.GetPayloadResult<{
        id: string
        bucketKey: string
        mediaType: $Enums.MediaType
        fileName: string
        mimeType: string
        fileSize: number
        isStale: boolean
        createdAt: Date
        updatedAt: Date
      }, ExtArgs["result"]["media"]>
      composites: {}
    };
export type MediaGetPayload<S extends boolean | null | undefined | MediaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MediaPayload, S>;
export type MediaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<MediaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
        select?: MediaCountAggregateInputType | true
      };

export interface MediaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Media'], meta: { name: 'Media' } };
    /**
     * Fields of the Media model
     */
    readonly fields: MediaFieldRefs;
    /**
     * Find zero or one Media that matches the filter.
     * @param {MediaFindUniqueArgs} args - Arguments to find a Media
     * @example
     * // Get one Media
     * const media = await prisma.media.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends MediaFindUniqueArgs>(args: Prisma.SelectSubset<T, MediaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find one Media that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {MediaFindUniqueOrThrowArgs} args - Arguments to find a Media
     * @example
     * // Get one Media
     * const media = await prisma.media.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends MediaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MediaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first Media that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaFindFirstArgs} args - Arguments to find a Media
     * @example
     * // Get one Media
     * const media = await prisma.media.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends MediaFindFirstArgs>(args?: Prisma.SelectSubset<T, MediaFindFirstArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first Media that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaFindFirstOrThrowArgs} args - Arguments to find a Media
     * @example
     * // Get one Media
     * const media = await prisma.media.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends MediaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MediaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find zero or more Media that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all Media
     * const media = await prisma.media.findMany()
     *
     * // Get first 10 Media
     * const media = await prisma.media.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const mediaWithIdOnly = await prisma.media.findMany({ select: { id: true } })
     */
    findMany<T extends MediaFindManyArgs>(args?: Prisma.SelectSubset<T, MediaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;
    /**
     * Create a Media.
     * @param {MediaCreateArgs} args - Arguments to create a Media.
     * @example
     * // Create one Media
     * const Media = await prisma.media.create({
     *   data: {
     *     // ... data to create a Media
     *   }
     * })
     */
    create<T extends MediaCreateArgs>(args: Prisma.SelectSubset<T, MediaCreateArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Create many Media.
     * @param {MediaCreateManyArgs} args - Arguments to create many Media.
     * @example
     * // Create many Media
     * const media = await prisma.media.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     */
    createMany<T extends MediaCreateManyArgs>(args?: Prisma.SelectSubset<T, MediaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Create many Media and returns the data saved in the database.
     * @param {MediaCreateManyAndReturnArgs} args - Arguments to create many Media.
     * @example
     * // Create many Media
     * const media = await prisma.media.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many Media and only return the `id`
     * const mediaWithIdOnly = await prisma.media.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    createManyAndReturn<T extends MediaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MediaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;
    /**
     * Delete a Media.
     * @param {MediaDeleteArgs} args - Arguments to delete one Media.
     * @example
     * // Delete one Media
     * const Media = await prisma.media.delete({
     *   where: {
     *     // ... filter to delete one Media
     *   }
     * })
     */
    delete<T extends MediaDeleteArgs>(args: Prisma.SelectSubset<T, MediaDeleteArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Update one Media.
     * @param {MediaUpdateArgs} args - Arguments to update one Media.
     * @example
     * // Update one Media
     * const media = await prisma.media.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    update<T extends MediaUpdateArgs>(args: Prisma.SelectSubset<T, MediaUpdateArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Delete zero or more Media.
     * @param {MediaDeleteManyArgs} args - Arguments to filter Media to delete.
     * @example
     * // Delete a few Media
     * const { count } = await prisma.media.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    deleteMany<T extends MediaDeleteManyArgs>(args?: Prisma.SelectSubset<T, MediaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more Media.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many Media
     * const media = await prisma.media.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    updateMany<T extends MediaUpdateManyArgs>(args: Prisma.SelectSubset<T, MediaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more Media and returns the data updated in the database.
     * @param {MediaUpdateManyAndReturnArgs} args - Arguments to update many Media.
     * @example
     * // Update many Media
     * const media = await prisma.media.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more Media and only return the `id`
     * const mediaWithIdOnly = await prisma.media.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    updateManyAndReturn<T extends MediaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MediaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;
    /**
     * Create or update one Media.
     * @param {MediaUpsertArgs} args - Arguments to update or create a Media.
     * @example
     * // Update or create a Media
     * const media = await prisma.media.upsert({
     *   create: {
     *     // ... data to create a Media
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the Media we want to update
     *   }
     * })
     */
    upsert<T extends MediaUpsertArgs>(args: Prisma.SelectSubset<T, MediaUpsertArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Count the number of Media.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaCountArgs} args - Arguments to filter Media to count.
     * @example
     * // Count the number of Media
     * const count = await prisma.media.count({
     *   where: {
     *     // ... the filter for the Media we want to count
     *   }
     * })
     */
    count<T extends MediaCountArgs>(args?: Prisma.Subset<T, MediaCountArgs>): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
          ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], MediaCountAggregateOutputType>
          : number
        >;
    /**
     * Allows you to perform aggregations operations on a Media.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     */
    aggregate<T extends MediaAggregateArgs>(args: Prisma.Subset<T, MediaAggregateArgs>): Prisma.PrismaPromise<GetMediaAggregateType<T>>;
    /**
     * Group by Media.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {MediaGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     */
    groupBy<T extends MediaGroupByArgs, HasSelectOrTake extends Prisma.Or<
          Prisma.Extends<'skip', Prisma.Keys<T>>,
          Prisma.Extends<'take', Prisma.Keys<T>>
        >, OrderByArg extends Prisma.True extends HasSelectOrTake
        ? { orderBy: MediaGroupByArgs['orderBy'] }
        : { orderBy?: MediaGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
        ? `Error: "by" must not be empty.`
        : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  'Field ',
                  P,
                  ` in "having" needs to be provided in "by"`,
                ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "skip", you also need to provide "orderBy"'
        : ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]>(args: Prisma.SubsetIntersection<T, MediaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMediaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
}

/**
 * The delegate class that acts as a "Promise-like" for Media.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MediaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    product<T extends Prisma.Media$productArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$productArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    image<T extends Prisma.Media$imageArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$imageArgs<ExtArgs>>): Prisma.Prisma__ImageClient<runtime.Types.Result.GetResult<Prisma.$ImagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    video<T extends Prisma.Media$videoArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$videoArgs<ExtArgs>>): Prisma.Prisma__VideoClient<runtime.Types.Result.GetResult<Prisma.$VideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    audio<T extends Prisma.Media$audioArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$audioArgs<ExtArgs>>): Prisma.Prisma__AudioClient<runtime.Types.Result.GetResult<Prisma.$AudioPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    document<T extends Prisma.Media$documentArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$documentArgs<ExtArgs>>): Prisma.Prisma__DocumentClient<runtime.Types.Result.GetResult<Prisma.$DocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    file<T extends Prisma.Media$fileArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Media$fileArgs<ExtArgs>>): Prisma.Prisma__FileClient<runtime.Types.Result.GetResult<Prisma.$FilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Media model
 */
export interface MediaFieldRefs {
    readonly id: Prisma.FieldRef<"Media", 'String'>;
    readonly bucketKey: Prisma.FieldRef<"Media", 'String'>;
    readonly mediaType: Prisma.FieldRef<"Media", 'MediaType'>;
    readonly fileName: Prisma.FieldRef<"Media", 'String'>;
    readonly mimeType: Prisma.FieldRef<"Media", 'String'>;
    readonly fileSize: Prisma.FieldRef<"Media", 'Int'>;
    readonly isStale: Prisma.FieldRef<"Media", 'Boolean'>;
    readonly createdAt: Prisma.FieldRef<"Media", 'DateTime'>;
    readonly updatedAt: Prisma.FieldRef<"Media", 'DateTime'>;
}

// Custom InputTypes
/**
 * Media findUnique
 */
export type MediaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter, which Media to fetch.
       */
      where: Prisma.MediaWhereUniqueInput
    };
/**
 * Media findUniqueOrThrow
 */
export type MediaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter, which Media to fetch.
       */
      where: Prisma.MediaWhereUniqueInput
    };
/**
 * Media findFirst
 */
export type MediaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter, which Media to fetch.
       */
      where?: Prisma.MediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of Media to fetch.
       */
      orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for Media.
       */
      cursor?: Prisma.MediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` Media from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` Media.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of Media.
       */
      distinct?: Prisma.MediaScalarFieldEnum | Prisma.MediaScalarFieldEnum[]
    };
/**
 * Media findFirstOrThrow
 */
export type MediaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter, which Media to fetch.
       */
      where?: Prisma.MediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of Media to fetch.
       */
      orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for Media.
       */
      cursor?: Prisma.MediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` Media from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` Media.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of Media.
       */
      distinct?: Prisma.MediaScalarFieldEnum | Prisma.MediaScalarFieldEnum[]
    };
/**
 * Media findMany
 */
export type MediaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter, which Media to fetch.
       */
      where?: Prisma.MediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of Media to fetch.
       */
      orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for listing Media.
       */
      cursor?: Prisma.MediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` Media from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` Media.
       */
      skip?: number
      distinct?: Prisma.MediaScalarFieldEnum | Prisma.MediaScalarFieldEnum[]
    };
/**
 * Media create
 */
export type MediaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * The data needed to create a Media.
       */
      data: Prisma.XOR<Prisma.MediaCreateInput, Prisma.MediaUncheckedCreateInput>
    };
/**
 * Media createMany
 */
export type MediaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to create many Media.
       */
      data: Prisma.MediaCreateManyInput | Prisma.MediaCreateManyInput[]
      skipDuplicates?: boolean
    };
/**
 * Media createManyAndReturn
 */
export type MediaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelectCreateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * The data used to create many Media.
       */
      data: Prisma.MediaCreateManyInput | Prisma.MediaCreateManyInput[]
      skipDuplicates?: boolean
    };
/**
 * Media update
 */
export type MediaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * The data needed to update a Media.
       */
      data: Prisma.XOR<Prisma.MediaUpdateInput, Prisma.MediaUncheckedUpdateInput>
      /**
       * Choose, which Media to update.
       */
      where: Prisma.MediaWhereUniqueInput
    };
/**
 * Media updateMany
 */
export type MediaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to update Media.
       */
      data: Prisma.XOR<Prisma.MediaUpdateManyMutationInput, Prisma.MediaUncheckedUpdateManyInput>
      /**
       * Filter which Media to update
       */
      where?: Prisma.MediaWhereInput
      /**
       * Limit how many Media to update.
       */
      limit?: number
    };
/**
 * Media updateManyAndReturn
 */
export type MediaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelectUpdateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * The data used to update Media.
       */
      data: Prisma.XOR<Prisma.MediaUpdateManyMutationInput, Prisma.MediaUncheckedUpdateManyInput>
      /**
       * Filter which Media to update
       */
      where?: Prisma.MediaWhereInput
      /**
       * Limit how many Media to update.
       */
      limit?: number
    };
/**
 * Media upsert
 */
export type MediaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * The filter to search for the Media to update in case it exists.
       */
      where: Prisma.MediaWhereUniqueInput
      /**
       * In case the Media found by the `where` argument doesn't exist, create a new Media with this data.
       */
      create: Prisma.XOR<Prisma.MediaCreateInput, Prisma.MediaUncheckedCreateInput>
      /**
       * In case the Media was found with the provided `where` argument, update it with this data.
       */
      update: Prisma.XOR<Prisma.MediaUpdateInput, Prisma.MediaUncheckedUpdateInput>
    };
/**
 * Media delete
 */
export type MediaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
      /**
       * Filter which Media to delete.
       */
      where: Prisma.MediaWhereUniqueInput
    };
/**
 * Media deleteMany
 */
export type MediaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which Media to delete
       */
      where?: Prisma.MediaWhereInput
      /**
       * Limit how many Media to delete.
       */
      limit?: number
    };
/**
 * Media.product
 */
export type Media$productArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      where?: Prisma.ProductVariantMediaWhereInput
    };
/**
 * Media.image
 */
export type Media$imageArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Image
       */
      select?: Prisma.ImageSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Image
       */
      omit?: Prisma.ImageOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ImageInclude<ExtArgs> | null
      where?: Prisma.ImageWhereInput
    };
/**
 * Media.video
 */
export type Media$videoArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Video
       */
      select?: Prisma.VideoSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Video
       */
      omit?: Prisma.VideoOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.VideoInclude<ExtArgs> | null
      where?: Prisma.VideoWhereInput
    };
/**
 * Media.audio
 */
export type Media$audioArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Audio
       */
      select?: Prisma.AudioSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Audio
       */
      omit?: Prisma.AudioOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.AudioInclude<ExtArgs> | null
      where?: Prisma.AudioWhereInput
    };
/**
 * Media.document
 */
export type Media$documentArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Document
       */
      select?: Prisma.DocumentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Document
       */
      omit?: Prisma.DocumentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.DocumentInclude<ExtArgs> | null
      where?: Prisma.DocumentWhereInput
    };
/**
 * Media.file
 */
export type Media$fileArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the File
       */
      select?: Prisma.FileSelect<ExtArgs> | null
      /**
       * Omit specific fields from the File
       */
      omit?: Prisma.FileOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.FileInclude<ExtArgs> | null
      where?: Prisma.FileWhereInput
    };
/**
 * Media without action
 */
export type MediaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the Media
       */
      select?: Prisma.MediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the Media
       */
      omit?: Prisma.MediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.MediaInclude<ExtArgs> | null
    };
