import $Types = runtime.Types;
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"
/**
 * Model ProductVariantMedia
 * @
 * @allow ('all', true)
 */
export type ProductVariantMediaModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductVariantMediaPayload>;
export type AggregateProductVariantMedia = {
      _count: ProductVariantMediaCountAggregateOutputType | null
      _avg: ProductVariantMediaAvgAggregateOutputType | null
      _sum: ProductVariantMediaSumAggregateOutputType | null
      _min: ProductVariantMediaMinAggregateOutputType | null
      _max: ProductVariantMediaMaxAggregateOutputType | null
    };
export type ProductVariantMediaAvgAggregateOutputType = {
      sortOrder: number | null
    };
export type ProductVariantMediaSumAggregateOutputType = {
      sortOrder: number | null
    };
export type ProductVariantMediaMinAggregateOutputType = {
      id: string | null
      isPrimary: boolean | null
      sortOrder: number | null
      productVariantId: string | null
      mediaId: string | null
    };
export type ProductVariantMediaMaxAggregateOutputType = {
      id: string | null
      isPrimary: boolean | null
      sortOrder: number | null
      productVariantId: string | null
      mediaId: string | null
    };
export type ProductVariantMediaCountAggregateOutputType = {
      id: number
      isPrimary: number
      sortOrder: number
      productVariantId: number
      mediaId: number
      _all: number
    };
export type ProductVariantMediaAvgAggregateInputType = {
      sortOrder?: true
    };
export type ProductVariantMediaSumAggregateInputType = {
      sortOrder?: true
    };
export type ProductVariantMediaMinAggregateInputType = {
      id?: true
      isPrimary?: true
      sortOrder?: true
      productVariantId?: true
      mediaId?: true
    };
export type ProductVariantMediaMaxAggregateInputType = {
      id?: true
      isPrimary?: true
      sortOrder?: true
      productVariantId?: true
      mediaId?: true
    };
export type ProductVariantMediaCountAggregateInputType = {
      id?: true
      isPrimary?: true
      sortOrder?: true
      productVariantId?: true
      mediaId?: true
      _all?: true
    };
export type ProductVariantMediaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which ProductVariantMedia to aggregate.
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantMedias to fetch.
       */
      orderBy?: Prisma.ProductVariantMediaOrderByWithRelationInput | Prisma.ProductVariantMediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the start position
       */
      cursor?: Prisma.ProductVariantMediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantMedias from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantMedias.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Count returned ProductVariantMedias
      **/
      _count?: true | ProductVariantMediaCountAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to average
      **/
      _avg?: ProductVariantMediaAvgAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to sum
      **/
      _sum?: ProductVariantMediaSumAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the minimum value
      **/
      _min?: ProductVariantMediaMinAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the maximum value
      **/
      _max?: ProductVariantMediaMaxAggregateInputType
    };
export type GetProductVariantMediaAggregateType<T extends ProductVariantMediaAggregateArgs> = {
          [P in keyof T & keyof AggregateProductVariantMedia]: P extends '_count' | 'count'
        ? T[P] extends true
          ? number
          : Prisma.GetScalarType<T[P], AggregateProductVariantMedia[P]>
        : Prisma.GetScalarType<T[P], AggregateProductVariantMedia[P]>
    };
export type ProductVariantMediaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      where?: Prisma.ProductVariantMediaWhereInput
      orderBy?: Prisma.ProductVariantMediaOrderByWithAggregationInput | Prisma.ProductVariantMediaOrderByWithAggregationInput[]
      by: Prisma.ProductVariantMediaScalarFieldEnum[] | Prisma.ProductVariantMediaScalarFieldEnum
      having?: Prisma.ProductVariantMediaScalarWhereWithAggregatesInput
      take?: number
      skip?: number
      _count?: ProductVariantMediaCountAggregateInputType | true
      _avg?: ProductVariantMediaAvgAggregateInputType
      _sum?: ProductVariantMediaSumAggregateInputType
      _min?: ProductVariantMediaMinAggregateInputType
      _max?: ProductVariantMediaMaxAggregateInputType
    };
export type ProductVariantMediaGroupByOutputType = {
      id: string
      isPrimary: boolean
      sortOrder: number
      productVariantId: string
      mediaId: string
      _count: ProductVariantMediaCountAggregateOutputType | null
      _avg: ProductVariantMediaAvgAggregateOutputType | null
      _sum: ProductVariantMediaSumAggregateOutputType | null
      _min: ProductVariantMediaMinAggregateOutputType | null
      _max: ProductVariantMediaMaxAggregateOutputType | null
    };
type GetProductVariantMediaGroupByPayload<T extends ProductVariantMediaGroupByArgs> = Prisma.PrismaPromise<
      Array<
        Prisma.PickEnumerable<ProductVariantMediaGroupByOutputType, T['by']> &
          {
            [P in ((keyof T) & (keyof ProductVariantMediaGroupByOutputType))]: P extends '_count'
              ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], ProductVariantMediaGroupByOutputType[P]>
              : Prisma.GetScalarType<T[P], ProductVariantMediaGroupByOutputType[P]>
          }
        >
      >;
export type ProductVariantMediaWhereInput = {
      AND?: Prisma.ProductVariantMediaWhereInput | Prisma.ProductVariantMediaWhereInput[]
      OR?: Prisma.ProductVariantMediaWhereInput[]
      NOT?: Prisma.ProductVariantMediaWhereInput | Prisma.ProductVariantMediaWhereInput[]
      id?: Prisma.StringFilter<"ProductVariantMedia"> | string
      isPrimary?: Prisma.BoolFilter<"ProductVariantMedia"> | boolean
      sortOrder?: Prisma.IntFilter<"ProductVariantMedia"> | number
      productVariantId?: Prisma.StringFilter<"ProductVariantMedia"> | string
      mediaId?: Prisma.StringFilter<"ProductVariantMedia"> | string
      productVariant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
      media?: Prisma.XOR<Prisma.MediaScalarRelationFilter, Prisma.MediaWhereInput>
    };
export type ProductVariantMediaOrderByWithRelationInput = {
      id?: Prisma.SortOrder
      isPrimary?: Prisma.SortOrder
      sortOrder?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
      productVariant?: Prisma.ProductVariantOrderByWithRelationInput
      media?: Prisma.MediaOrderByWithRelationInput
    };
export type ProductVariantMediaWhereUniqueInput = Prisma.AtLeast<{
      id?: string
      mediaId?: string
      AND?: Prisma.ProductVariantMediaWhereInput | Prisma.ProductVariantMediaWhereInput[]
      OR?: Prisma.ProductVariantMediaWhereInput[]
      NOT?: Prisma.ProductVariantMediaWhereInput | Prisma.ProductVariantMediaWhereInput[]
      isPrimary?: Prisma.BoolFilter<"ProductVariantMedia"> | boolean
      sortOrder?: Prisma.IntFilter<"ProductVariantMedia"> | number
      productVariantId?: Prisma.StringFilter<"ProductVariantMedia"> | string
      productVariant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
      media?: Prisma.XOR<Prisma.MediaScalarRelationFilter, Prisma.MediaWhereInput>
    }, "id" | "mediaId">;
export type ProductVariantMediaOrderByWithAggregationInput = {
      id?: Prisma.SortOrder
      isPrimary?: Prisma.SortOrder
      sortOrder?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
      _count?: Prisma.ProductVariantMediaCountOrderByAggregateInput
      _avg?: Prisma.ProductVariantMediaAvgOrderByAggregateInput
      _max?: Prisma.ProductVariantMediaMaxOrderByAggregateInput
      _min?: Prisma.ProductVariantMediaMinOrderByAggregateInput
      _sum?: Prisma.ProductVariantMediaSumOrderByAggregateInput
    };
export type ProductVariantMediaScalarWhereWithAggregatesInput = {
      AND?: Prisma.ProductVariantMediaScalarWhereWithAggregatesInput | Prisma.ProductVariantMediaScalarWhereWithAggregatesInput[]
      OR?: Prisma.ProductVariantMediaScalarWhereWithAggregatesInput[]
      NOT?: Prisma.ProductVariantMediaScalarWhereWithAggregatesInput | Prisma.ProductVariantMediaScalarWhereWithAggregatesInput[]
      id?: Prisma.StringWithAggregatesFilter<"ProductVariantMedia"> | string
      isPrimary?: Prisma.BoolWithAggregatesFilter<"ProductVariantMedia"> | boolean
      sortOrder?: Prisma.IntWithAggregatesFilter<"ProductVariantMedia"> | number
      productVariantId?: Prisma.StringWithAggregatesFilter<"ProductVariantMedia"> | string
      mediaId?: Prisma.StringWithAggregatesFilter<"ProductVariantMedia"> | string
    };
export type ProductVariantMediaCreateInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      productVariant: Prisma.ProductVariantCreateNestedOneWithoutMediaItemsInput
      media: Prisma.MediaCreateNestedOneWithoutProductInput
    };
export type ProductVariantMediaUncheckedCreateInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      productVariantId: string
      mediaId: string
    };
export type ProductVariantMediaUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      productVariant?: Prisma.ProductVariantUpdateOneRequiredWithoutMediaItemsNestedInput
      media?: Prisma.MediaUpdateOneRequiredWithoutProductNestedInput
    };
export type ProductVariantMediaUncheckedUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantMediaCreateManyInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      productVariantId: string
      mediaId: string
    };
export type ProductVariantMediaUpdateManyMutationInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
    };
export type ProductVariantMediaUncheckedUpdateManyInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantMediaNullableScalarRelationFilter = {
      is?: Prisma.ProductVariantMediaWhereInput | null
      isNot?: Prisma.ProductVariantMediaWhereInput | null
    };
export type ProductVariantMediaListRelationFilter = {
      every?: Prisma.ProductVariantMediaWhereInput
      some?: Prisma.ProductVariantMediaWhereInput
      none?: Prisma.ProductVariantMediaWhereInput
    };
export type ProductVariantMediaOrderByRelationAggregateInput = {
      _count?: Prisma.SortOrder
    };
export type ProductVariantMediaCountOrderByAggregateInput = {
      id?: Prisma.SortOrder
      isPrimary?: Prisma.SortOrder
      sortOrder?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantMediaAvgOrderByAggregateInput = {
      sortOrder?: Prisma.SortOrder
    };
export type ProductVariantMediaMaxOrderByAggregateInput = {
      id?: Prisma.SortOrder
      isPrimary?: Prisma.SortOrder
      sortOrder?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantMediaMinOrderByAggregateInput = {
      id?: Prisma.SortOrder
      isPrimary?: Prisma.SortOrder
      sortOrder?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantMediaSumOrderByAggregateInput = {
      sortOrder?: Prisma.SortOrder
    };
export type ProductVariantMediaCreateNestedOneWithoutMediaInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutMediaInput
      connect?: Prisma.ProductVariantMediaWhereUniqueInput
    };
export type ProductVariantMediaUncheckedCreateNestedOneWithoutMediaInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutMediaInput
      connect?: Prisma.ProductVariantMediaWhereUniqueInput
    };
export type ProductVariantMediaUpdateOneWithoutMediaNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutMediaInput
      upsert?: Prisma.ProductVariantMediaUpsertWithoutMediaInput
      disconnect?: Prisma.ProductVariantMediaWhereInput | boolean
      delete?: Prisma.ProductVariantMediaWhereInput | boolean
      connect?: Prisma.ProductVariantMediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.ProductVariantMediaUpdateToOneWithWhereWithoutMediaInput, Prisma.ProductVariantMediaUpdateWithoutMediaInput>, Prisma.ProductVariantMediaUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantMediaUncheckedUpdateOneWithoutMediaNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutMediaInput
      upsert?: Prisma.ProductVariantMediaUpsertWithoutMediaInput
      disconnect?: Prisma.ProductVariantMediaWhereInput | boolean
      delete?: Prisma.ProductVariantMediaWhereInput | boolean
      connect?: Prisma.ProductVariantMediaWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.ProductVariantMediaUpdateToOneWithWhereWithoutMediaInput, Prisma.ProductVariantMediaUpdateWithoutMediaInput>, Prisma.ProductVariantMediaUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantMediaCreateNestedManyWithoutProductVariantInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantMediaCreateWithoutProductVariantInput[] | Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantMediaCreateManyProductVariantInputEnvelope
      connect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
    };
export type ProductVariantMediaUncheckedCreateNestedManyWithoutProductVariantInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantMediaCreateWithoutProductVariantInput[] | Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantMediaCreateManyProductVariantInputEnvelope
      connect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
    };
export type ProductVariantMediaUpdateManyWithoutProductVariantNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantMediaCreateWithoutProductVariantInput[] | Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput[]
      upsert?: Prisma.ProductVariantMediaUpsertWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantMediaUpsertWithWhereUniqueWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantMediaCreateManyProductVariantInputEnvelope
      set?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      disconnect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      delete?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      connect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      update?: Prisma.ProductVariantMediaUpdateWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantMediaUpdateWithWhereUniqueWithoutProductVariantInput[]
      updateMany?: Prisma.ProductVariantMediaUpdateManyWithWhereWithoutProductVariantInput | Prisma.ProductVariantMediaUpdateManyWithWhereWithoutProductVariantInput[]
      deleteMany?: Prisma.ProductVariantMediaScalarWhereInput | Prisma.ProductVariantMediaScalarWhereInput[]
    };
export type ProductVariantMediaUncheckedUpdateManyWithoutProductVariantNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantMediaCreateWithoutProductVariantInput[] | Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantMediaCreateOrConnectWithoutProductVariantInput[]
      upsert?: Prisma.ProductVariantMediaUpsertWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantMediaUpsertWithWhereUniqueWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantMediaCreateManyProductVariantInputEnvelope
      set?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      disconnect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      delete?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      connect?: Prisma.ProductVariantMediaWhereUniqueInput | Prisma.ProductVariantMediaWhereUniqueInput[]
      update?: Prisma.ProductVariantMediaUpdateWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantMediaUpdateWithWhereUniqueWithoutProductVariantInput[]
      updateMany?: Prisma.ProductVariantMediaUpdateManyWithWhereWithoutProductVariantInput | Prisma.ProductVariantMediaUpdateManyWithWhereWithoutProductVariantInput[]
      deleteMany?: Prisma.ProductVariantMediaScalarWhereInput | Prisma.ProductVariantMediaScalarWhereInput[]
    };
export type ProductVariantMediaCreateWithoutMediaInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      productVariant: Prisma.ProductVariantCreateNestedOneWithoutMediaItemsInput
    };
export type ProductVariantMediaUncheckedCreateWithoutMediaInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      productVariantId: string
    };
export type ProductVariantMediaCreateOrConnectWithoutMediaInput = {
      where: Prisma.ProductVariantMediaWhereUniqueInput
      create: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
    };
export type ProductVariantMediaUpsertWithoutMediaInput = {
      update: Prisma.XOR<Prisma.ProductVariantMediaUpdateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedUpdateWithoutMediaInput>
      create: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedCreateWithoutMediaInput>
      where?: Prisma.ProductVariantMediaWhereInput
    };
export type ProductVariantMediaUpdateToOneWithWhereWithoutMediaInput = {
      where?: Prisma.ProductVariantMediaWhereInput
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateWithoutMediaInput, Prisma.ProductVariantMediaUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantMediaUpdateWithoutMediaInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      productVariant?: Prisma.ProductVariantUpdateOneRequiredWithoutMediaItemsNestedInput
    };
export type ProductVariantMediaUncheckedUpdateWithoutMediaInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantMediaCreateWithoutProductVariantInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      media: Prisma.MediaCreateNestedOneWithoutProductInput
    };
export type ProductVariantMediaUncheckedCreateWithoutProductVariantInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      mediaId: string
    };
export type ProductVariantMediaCreateOrConnectWithoutProductVariantInput = {
      where: Prisma.ProductVariantMediaWhereUniqueInput
      create: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput>
    };
export type ProductVariantMediaCreateManyProductVariantInputEnvelope = {
      data: Prisma.ProductVariantMediaCreateManyProductVariantInput | Prisma.ProductVariantMediaCreateManyProductVariantInput[]
      skipDuplicates?: boolean
    };
export type ProductVariantMediaUpsertWithWhereUniqueWithoutProductVariantInput = {
      where: Prisma.ProductVariantMediaWhereUniqueInput
      update: Prisma.XOR<Prisma.ProductVariantMediaUpdateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedUpdateWithoutProductVariantInput>
      create: Prisma.XOR<Prisma.ProductVariantMediaCreateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedCreateWithoutProductVariantInput>
    };
export type ProductVariantMediaUpdateWithWhereUniqueWithoutProductVariantInput = {
      where: Prisma.ProductVariantMediaWhereUniqueInput
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateWithoutProductVariantInput, Prisma.ProductVariantMediaUncheckedUpdateWithoutProductVariantInput>
    };
export type ProductVariantMediaUpdateManyWithWhereWithoutProductVariantInput = {
      where: Prisma.ProductVariantMediaScalarWhereInput
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateManyMutationInput, Prisma.ProductVariantMediaUncheckedUpdateManyWithoutProductVariantInput>
    };
export type ProductVariantMediaScalarWhereInput = {
      AND?: Prisma.ProductVariantMediaScalarWhereInput | Prisma.ProductVariantMediaScalarWhereInput[]
      OR?: Prisma.ProductVariantMediaScalarWhereInput[]
      NOT?: Prisma.ProductVariantMediaScalarWhereInput | Prisma.ProductVariantMediaScalarWhereInput[]
      id?: Prisma.StringFilter<"ProductVariantMedia"> | string
      isPrimary?: Prisma.BoolFilter<"ProductVariantMedia"> | boolean
      sortOrder?: Prisma.IntFilter<"ProductVariantMedia"> | number
      productVariantId?: Prisma.StringFilter<"ProductVariantMedia"> | string
      mediaId?: Prisma.StringFilter<"ProductVariantMedia"> | string
    };
export type ProductVariantMediaCreateManyProductVariantInput = {
      id?: string
      isPrimary?: boolean
      sortOrder?: number
      mediaId: string
    };
export type ProductVariantMediaUpdateWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      media?: Prisma.MediaUpdateOneRequiredWithoutProductNestedInput
    };
export type ProductVariantMediaUncheckedUpdateWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantMediaUncheckedUpdateManyWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      isPrimary?: Prisma.BoolFieldUpdateOperationsInput | boolean
      sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantMediaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      isPrimary?: boolean
      sortOrder?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantMedia"]>;
export type ProductVariantMediaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      isPrimary?: boolean
      sortOrder?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantMedia"]>;
export type ProductVariantMediaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      isPrimary?: boolean
      sortOrder?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantMedia"]>;
export type ProductVariantMediaSelectScalar = {
      id?: boolean
      isPrimary?: boolean
      sortOrder?: boolean
      productVariantId?: boolean
      mediaId?: boolean
    };
export type ProductVariantMediaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "isPrimary" | "sortOrder" | "productVariantId" | "mediaId", ExtArgs["result"]["productVariantMedia"]>;
export type ProductVariantMediaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type ProductVariantMediaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type ProductVariantMediaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type $ProductVariantMediaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      name: "ProductVariantMedia"
      objects: {
        productVariant: Prisma.$ProductVariantPayload<ExtArgs>
        media: Prisma.$MediaPayload<ExtArgs>
      }
      scalars: runtime.Types.Extensions.GetPayloadResult<{
        id: string
        isPrimary: boolean
        sortOrder: number
        productVariantId: string
        mediaId: string
      }, ExtArgs["result"]["productVariantMedia"]>
      composites: {}
    };
export type ProductVariantMediaGetPayload<S extends boolean | null | undefined | ProductVariantMediaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload, S>;
export type ProductVariantMediaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<ProductVariantMediaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
        select?: ProductVariantMediaCountAggregateInputType | true
      };

export interface ProductVariantMediaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductVariantMedia'], meta: { name: 'ProductVariantMedia' } };
    /**
     * Fields of the ProductVariantMedia model
     */
    readonly fields: ProductVariantMediaFieldRefs;
    /**
     * Find zero or one ProductVariantMedia that matches the filter.
     * @param {ProductVariantMediaFindUniqueArgs} args - Arguments to find a ProductVariantMedia
     * @example
     * // Get one ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends ProductVariantMediaFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find one ProductVariantMedia that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {ProductVariantMediaFindUniqueOrThrowArgs} args - Arguments to find a ProductVariantMedia
     * @example
     * // Get one ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends ProductVariantMediaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first ProductVariantMedia that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaFindFirstArgs} args - Arguments to find a ProductVariantMedia
     * @example
     * // Get one ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends ProductVariantMediaFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first ProductVariantMedia that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaFindFirstOrThrowArgs} args - Arguments to find a ProductVariantMedia
     * @example
     * // Get one ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends ProductVariantMediaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find zero or more ProductVariantMedias that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all ProductVariantMedias
     * const productVariantMedias = await prisma.productVariantMedia.findMany()
     *
     * // Get first 10 ProductVariantMedias
     * const productVariantMedias = await prisma.productVariantMedia.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const productVariantMediaWithIdOnly = await prisma.productVariantMedia.findMany({ select: { id: true } })
     */
    findMany<T extends ProductVariantMediaFindManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;
    /**
     * Create a ProductVariantMedia.
     * @param {ProductVariantMediaCreateArgs} args - Arguments to create a ProductVariantMedia.
     * @example
     * // Create one ProductVariantMedia
     * const ProductVariantMedia = await prisma.productVariantMedia.create({
     *   data: {
     *     // ... data to create a ProductVariantMedia
     *   }
     * })
     */
    create<T extends ProductVariantMediaCreateArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaCreateArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Create many ProductVariantMedias.
     * @param {ProductVariantMediaCreateManyArgs} args - Arguments to create many ProductVariantMedias.
     * @example
     * // Create many ProductVariantMedias
     * const productVariantMedia = await prisma.productVariantMedia.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     */
    createMany<T extends ProductVariantMediaCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Create many ProductVariantMedias and returns the data saved in the database.
     * @param {ProductVariantMediaCreateManyAndReturnArgs} args - Arguments to create many ProductVariantMedias.
     * @example
     * // Create many ProductVariantMedias
     * const productVariantMedia = await prisma.productVariantMedia.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many ProductVariantMedias and only return the `id`
     * const productVariantMediaWithIdOnly = await prisma.productVariantMedia.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    createManyAndReturn<T extends ProductVariantMediaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;
    /**
     * Delete a ProductVariantMedia.
     * @param {ProductVariantMediaDeleteArgs} args - Arguments to delete one ProductVariantMedia.
     * @example
     * // Delete one ProductVariantMedia
     * const ProductVariantMedia = await prisma.productVariantMedia.delete({
     *   where: {
     *     // ... filter to delete one ProductVariantMedia
     *   }
     * })
     */
    delete<T extends ProductVariantMediaDeleteArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Update one ProductVariantMedia.
     * @param {ProductVariantMediaUpdateArgs} args - Arguments to update one ProductVariantMedia.
     * @example
     * // Update one ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    update<T extends ProductVariantMediaUpdateArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Delete zero or more ProductVariantMedias.
     * @param {ProductVariantMediaDeleteManyArgs} args - Arguments to filter ProductVariantMedias to delete.
     * @example
     * // Delete a few ProductVariantMedias
     * const { count } = await prisma.productVariantMedia.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    deleteMany<T extends ProductVariantMediaDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantMediaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more ProductVariantMedias.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many ProductVariantMedias
     * const productVariantMedia = await prisma.productVariantMedia.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    updateMany<T extends ProductVariantMediaUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more ProductVariantMedias and returns the data updated in the database.
     * @param {ProductVariantMediaUpdateManyAndReturnArgs} args - Arguments to update many ProductVariantMedias.
     * @example
     * // Update many ProductVariantMedias
     * const productVariantMedia = await prisma.productVariantMedia.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more ProductVariantMedias and only return the `id`
     * const productVariantMediaWithIdOnly = await prisma.productVariantMedia.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    updateManyAndReturn<T extends ProductVariantMediaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;
    /**
     * Create or update one ProductVariantMedia.
     * @param {ProductVariantMediaUpsertArgs} args - Arguments to update or create a ProductVariantMedia.
     * @example
     * // Update or create a ProductVariantMedia
     * const productVariantMedia = await prisma.productVariantMedia.upsert({
     *   create: {
     *     // ... data to create a ProductVariantMedia
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the ProductVariantMedia we want to update
     *   }
     * })
     */
    upsert<T extends ProductVariantMediaUpsertArgs>(args: Prisma.SelectSubset<T, ProductVariantMediaUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductVariantMediaClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantMediaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Count the number of ProductVariantMedias.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaCountArgs} args - Arguments to filter ProductVariantMedias to count.
     * @example
     * // Count the number of ProductVariantMedias
     * const count = await prisma.productVariantMedia.count({
     *   where: {
     *     // ... the filter for the ProductVariantMedias we want to count
     *   }
     * })
     */
    count<T extends ProductVariantMediaCountArgs>(args?: Prisma.Subset<T, ProductVariantMediaCountArgs>): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
          ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], ProductVariantMediaCountAggregateOutputType>
          : number
        >;
    /**
     * Allows you to perform aggregations operations on a ProductVariantMedia.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     */
    aggregate<T extends ProductVariantMediaAggregateArgs>(args: Prisma.Subset<T, ProductVariantMediaAggregateArgs>): Prisma.PrismaPromise<GetProductVariantMediaAggregateType<T>>;
    /**
     * Group by ProductVariantMedia.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantMediaGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     */
    groupBy<T extends ProductVariantMediaGroupByArgs, HasSelectOrTake extends Prisma.Or<
          Prisma.Extends<'skip', Prisma.Keys<T>>,
          Prisma.Extends<'take', Prisma.Keys<T>>
        >, OrderByArg extends Prisma.True extends HasSelectOrTake
        ? { orderBy: ProductVariantMediaGroupByArgs['orderBy'] }
        : { orderBy?: ProductVariantMediaGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
        ? `Error: "by" must not be empty.`
        : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  'Field ',
                  P,
                  ` in "having" needs to be provided in "by"`,
                ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "skip", you also need to provide "orderBy"'
        : ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]>(args: Prisma.SubsetIntersection<T, ProductVariantMediaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductVariantMediaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductVariantMedia.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductVariantMediaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    productVariant<T extends Prisma.ProductVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductVariantClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>;
    media<T extends Prisma.MediaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MediaDefaultArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ProductVariantMedia model
 */
export interface ProductVariantMediaFieldRefs {
    readonly id: Prisma.FieldRef<"ProductVariantMedia", 'String'>;
    readonly isPrimary: Prisma.FieldRef<"ProductVariantMedia", 'Boolean'>;
    readonly sortOrder: Prisma.FieldRef<"ProductVariantMedia", 'Int'>;
    readonly productVariantId: Prisma.FieldRef<"ProductVariantMedia", 'String'>;
    readonly mediaId: Prisma.FieldRef<"ProductVariantMedia", 'String'>;
}

// Custom InputTypes
/**
 * ProductVariantMedia findUnique
 */
export type ProductVariantMediaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantMedia to fetch.
       */
      where: Prisma.ProductVariantMediaWhereUniqueInput
    };
/**
 * ProductVariantMedia findUniqueOrThrow
 */
export type ProductVariantMediaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantMedia to fetch.
       */
      where: Prisma.ProductVariantMediaWhereUniqueInput
    };
/**
 * ProductVariantMedia findFirst
 */
export type ProductVariantMediaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantMedia to fetch.
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantMedias to fetch.
       */
      orderBy?: Prisma.ProductVariantMediaOrderByWithRelationInput | Prisma.ProductVariantMediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for ProductVariantMedias.
       */
      cursor?: Prisma.ProductVariantMediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantMedias from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantMedias.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of ProductVariantMedias.
       */
      distinct?: Prisma.ProductVariantMediaScalarFieldEnum | Prisma.ProductVariantMediaScalarFieldEnum[]
    };
/**
 * ProductVariantMedia findFirstOrThrow
 */
export type ProductVariantMediaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantMedia to fetch.
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantMedias to fetch.
       */
      orderBy?: Prisma.ProductVariantMediaOrderByWithRelationInput | Prisma.ProductVariantMediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for ProductVariantMedias.
       */
      cursor?: Prisma.ProductVariantMediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantMedias from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantMedias.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of ProductVariantMedias.
       */
      distinct?: Prisma.ProductVariantMediaScalarFieldEnum | Prisma.ProductVariantMediaScalarFieldEnum[]
    };
/**
 * ProductVariantMedia findMany
 */
export type ProductVariantMediaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantMedias to fetch.
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantMedias to fetch.
       */
      orderBy?: Prisma.ProductVariantMediaOrderByWithRelationInput | Prisma.ProductVariantMediaOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for listing ProductVariantMedias.
       */
      cursor?: Prisma.ProductVariantMediaWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantMedias from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantMedias.
       */
      skip?: number
      distinct?: Prisma.ProductVariantMediaScalarFieldEnum | Prisma.ProductVariantMediaScalarFieldEnum[]
    };
/**
 * ProductVariantMedia create
 */
export type ProductVariantMediaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * The data needed to create a ProductVariantMedia.
       */
      data: Prisma.XOR<Prisma.ProductVariantMediaCreateInput, Prisma.ProductVariantMediaUncheckedCreateInput>
    };
/**
 * ProductVariantMedia createMany
 */
export type ProductVariantMediaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to create many ProductVariantMedias.
       */
      data: Prisma.ProductVariantMediaCreateManyInput | Prisma.ProductVariantMediaCreateManyInput[]
      skipDuplicates?: boolean
    };
/**
 * ProductVariantMedia createManyAndReturn
 */
export type ProductVariantMediaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelectCreateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * The data used to create many ProductVariantMedias.
       */
      data: Prisma.ProductVariantMediaCreateManyInput | Prisma.ProductVariantMediaCreateManyInput[]
      skipDuplicates?: boolean
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaIncludeCreateManyAndReturn<ExtArgs> | null
    };
/**
 * ProductVariantMedia update
 */
export type ProductVariantMediaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * The data needed to update a ProductVariantMedia.
       */
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateInput, Prisma.ProductVariantMediaUncheckedUpdateInput>
      /**
       * Choose, which ProductVariantMedia to update.
       */
      where: Prisma.ProductVariantMediaWhereUniqueInput
    };
/**
 * ProductVariantMedia updateMany
 */
export type ProductVariantMediaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to update ProductVariantMedias.
       */
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateManyMutationInput, Prisma.ProductVariantMediaUncheckedUpdateManyInput>
      /**
       * Filter which ProductVariantMedias to update
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * Limit how many ProductVariantMedias to update.
       */
      limit?: number
    };
/**
 * ProductVariantMedia updateManyAndReturn
 */
export type ProductVariantMediaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelectUpdateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * The data used to update ProductVariantMedias.
       */
      data: Prisma.XOR<Prisma.ProductVariantMediaUpdateManyMutationInput, Prisma.ProductVariantMediaUncheckedUpdateManyInput>
      /**
       * Filter which ProductVariantMedias to update
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * Limit how many ProductVariantMedias to update.
       */
      limit?: number
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaIncludeUpdateManyAndReturn<ExtArgs> | null
    };
/**
 * ProductVariantMedia upsert
 */
export type ProductVariantMediaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * The filter to search for the ProductVariantMedia to update in case it exists.
       */
      where: Prisma.ProductVariantMediaWhereUniqueInput
      /**
       * In case the ProductVariantMedia found by the `where` argument doesn't exist, create a new ProductVariantMedia with this data.
       */
      create: Prisma.XOR<Prisma.ProductVariantMediaCreateInput, Prisma.ProductVariantMediaUncheckedCreateInput>
      /**
       * In case the ProductVariantMedia was found with the provided `where` argument, update it with this data.
       */
      update: Prisma.XOR<Prisma.ProductVariantMediaUpdateInput, Prisma.ProductVariantMediaUncheckedUpdateInput>
    };
/**
 * ProductVariantMedia delete
 */
export type ProductVariantMediaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
      /**
       * Filter which ProductVariantMedia to delete.
       */
      where: Prisma.ProductVariantMediaWhereUniqueInput
    };
/**
 * ProductVariantMedia deleteMany
 */
export type ProductVariantMediaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which ProductVariantMedias to delete
       */
      where?: Prisma.ProductVariantMediaWhereInput
      /**
       * Limit how many ProductVariantMedias to delete.
       */
      limit?: number
    };
/**
 * ProductVariantMedia without action
 */
export type ProductVariantMediaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantMedia
       */
      select?: Prisma.ProductVariantMediaSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantMedia
       */
      omit?: Prisma.ProductVariantMediaOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantMediaInclude<ExtArgs> | null
    };
