import $Types = runtime.Types;
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"
/**
 * Model ProductVariantAttachment
 * @
 * @allow ('all', true)
 */
export type ProductVariantAttachmentModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductVariantAttachmentPayload>;
export type AggregateProductVariantAttachment = {
      _count: ProductVariantAttachmentCountAggregateOutputType | null
      _min: ProductVariantAttachmentMinAggregateOutputType | null
      _max: ProductVariantAttachmentMaxAggregateOutputType | null
    };
export type ProductVariantAttachmentMinAggregateOutputType = {
      id: string | null
      productVariantId: string | null
      mediaId: string | null
    };
export type ProductVariantAttachmentMaxAggregateOutputType = {
      id: string | null
      productVariantId: string | null
      mediaId: string | null
    };
export type ProductVariantAttachmentCountAggregateOutputType = {
      id: number
      productVariantId: number
      mediaId: number
      _all: number
    };
export type ProductVariantAttachmentMinAggregateInputType = {
      id?: true
      productVariantId?: true
      mediaId?: true
    };
export type ProductVariantAttachmentMaxAggregateInputType = {
      id?: true
      productVariantId?: true
      mediaId?: true
    };
export type ProductVariantAttachmentCountAggregateInputType = {
      id?: true
      productVariantId?: true
      mediaId?: true
      _all?: true
    };
export type ProductVariantAttachmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which ProductVariantAttachment to aggregate.
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantAttachments to fetch.
       */
      orderBy?: Prisma.ProductVariantAttachmentOrderByWithRelationInput | Prisma.ProductVariantAttachmentOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the start position
       */
      cursor?: Prisma.ProductVariantAttachmentWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantAttachments from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantAttachments.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Count returned ProductVariantAttachments
      **/
      _count?: true | ProductVariantAttachmentCountAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the minimum value
      **/
      _min?: ProductVariantAttachmentMinAggregateInputType
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
       * 
       * Select which fields to find the maximum value
      **/
      _max?: ProductVariantAttachmentMaxAggregateInputType
    };
export type GetProductVariantAttachmentAggregateType<T extends ProductVariantAttachmentAggregateArgs> = {
          [P in keyof T & keyof AggregateProductVariantAttachment]: P extends '_count' | 'count'
        ? T[P] extends true
          ? number
          : Prisma.GetScalarType<T[P], AggregateProductVariantAttachment[P]>
        : Prisma.GetScalarType<T[P], AggregateProductVariantAttachment[P]>
    };
export type ProductVariantAttachmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      where?: Prisma.ProductVariantAttachmentWhereInput
      orderBy?: Prisma.ProductVariantAttachmentOrderByWithAggregationInput | Prisma.ProductVariantAttachmentOrderByWithAggregationInput[]
      by: Prisma.ProductVariantAttachmentScalarFieldEnum[] | Prisma.ProductVariantAttachmentScalarFieldEnum
      having?: Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput
      take?: number
      skip?: number
      _count?: ProductVariantAttachmentCountAggregateInputType | true
      _min?: ProductVariantAttachmentMinAggregateInputType
      _max?: ProductVariantAttachmentMaxAggregateInputType
    };
export type ProductVariantAttachmentGroupByOutputType = {
      id: string
      productVariantId: string
      mediaId: string
      _count: ProductVariantAttachmentCountAggregateOutputType | null
      _min: ProductVariantAttachmentMinAggregateOutputType | null
      _max: ProductVariantAttachmentMaxAggregateOutputType | null
    };
type GetProductVariantAttachmentGroupByPayload<T extends ProductVariantAttachmentGroupByArgs> = Prisma.PrismaPromise<
      Array<
        Prisma.PickEnumerable<ProductVariantAttachmentGroupByOutputType, T['by']> &
          {
            [P in ((keyof T) & (keyof ProductVariantAttachmentGroupByOutputType))]: P extends '_count'
              ? T[P] extends boolean
                ? number
                : Prisma.GetScalarType<T[P], ProductVariantAttachmentGroupByOutputType[P]>
              : Prisma.GetScalarType<T[P], ProductVariantAttachmentGroupByOutputType[P]>
          }
        >
      >;
export type ProductVariantAttachmentWhereInput = {
      AND?: Prisma.ProductVariantAttachmentWhereInput | Prisma.ProductVariantAttachmentWhereInput[]
      OR?: Prisma.ProductVariantAttachmentWhereInput[]
      NOT?: Prisma.ProductVariantAttachmentWhereInput | Prisma.ProductVariantAttachmentWhereInput[]
      id?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      productVariantId?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      mediaId?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      productVariant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
      media?: Prisma.XOR<Prisma.MediaScalarRelationFilter, Prisma.MediaWhereInput>
    };
export type ProductVariantAttachmentOrderByWithRelationInput = {
      id?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
      productVariant?: Prisma.ProductVariantOrderByWithRelationInput
      media?: Prisma.MediaOrderByWithRelationInput
    };
export type ProductVariantAttachmentWhereUniqueInput = Prisma.AtLeast<{
      id?: string
      mediaId?: string
      AND?: Prisma.ProductVariantAttachmentWhereInput | Prisma.ProductVariantAttachmentWhereInput[]
      OR?: Prisma.ProductVariantAttachmentWhereInput[]
      NOT?: Prisma.ProductVariantAttachmentWhereInput | Prisma.ProductVariantAttachmentWhereInput[]
      productVariantId?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      productVariant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
      media?: Prisma.XOR<Prisma.MediaScalarRelationFilter, Prisma.MediaWhereInput>
    }, "id" | "mediaId">;
export type ProductVariantAttachmentOrderByWithAggregationInput = {
      id?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
      _count?: Prisma.ProductVariantAttachmentCountOrderByAggregateInput
      _max?: Prisma.ProductVariantAttachmentMaxOrderByAggregateInput
      _min?: Prisma.ProductVariantAttachmentMinOrderByAggregateInput
    };
export type ProductVariantAttachmentScalarWhereWithAggregatesInput = {
      AND?: Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput | Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput[]
      OR?: Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput[]
      NOT?: Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput | Prisma.ProductVariantAttachmentScalarWhereWithAggregatesInput[]
      id?: Prisma.StringWithAggregatesFilter<"ProductVariantAttachment"> | string
      productVariantId?: Prisma.StringWithAggregatesFilter<"ProductVariantAttachment"> | string
      mediaId?: Prisma.StringWithAggregatesFilter<"ProductVariantAttachment"> | string
    };
export type ProductVariantAttachmentCreateInput = {
      id?: string
      productVariant: Prisma.ProductVariantCreateNestedOneWithoutAttachmentsInput
      media: Prisma.MediaCreateNestedOneWithoutProductVariantAttachmentInput
    };
export type ProductVariantAttachmentUncheckedCreateInput = {
      id?: string
      productVariantId: string
      mediaId: string
    };
export type ProductVariantAttachmentUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      productVariant?: Prisma.ProductVariantUpdateOneRequiredWithoutAttachmentsNestedInput
      media?: Prisma.MediaUpdateOneRequiredWithoutProductVariantAttachmentNestedInput
    };
export type ProductVariantAttachmentUncheckedUpdateInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentCreateManyInput = {
      id?: string
      productVariantId: string
      mediaId: string
    };
export type ProductVariantAttachmentUpdateManyMutationInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentUncheckedUpdateManyInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentNullableScalarRelationFilter = {
      is?: Prisma.ProductVariantAttachmentWhereInput | null
      isNot?: Prisma.ProductVariantAttachmentWhereInput | null
    };
export type ProductVariantAttachmentListRelationFilter = {
      every?: Prisma.ProductVariantAttachmentWhereInput
      some?: Prisma.ProductVariantAttachmentWhereInput
      none?: Prisma.ProductVariantAttachmentWhereInput
    };
export type ProductVariantAttachmentOrderByRelationAggregateInput = {
      _count?: Prisma.SortOrder
    };
export type ProductVariantAttachmentCountOrderByAggregateInput = {
      id?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantAttachmentMaxOrderByAggregateInput = {
      id?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantAttachmentMinOrderByAggregateInput = {
      id?: Prisma.SortOrder
      productVariantId?: Prisma.SortOrder
      mediaId?: Prisma.SortOrder
    };
export type ProductVariantAttachmentCreateNestedOneWithoutMediaInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutMediaInput
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
export type ProductVariantAttachmentUncheckedCreateNestedOneWithoutMediaInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutMediaInput
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
export type ProductVariantAttachmentUpdateOneWithoutMediaNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutMediaInput
      upsert?: Prisma.ProductVariantAttachmentUpsertWithoutMediaInput
      disconnect?: Prisma.ProductVariantAttachmentWhereInput | boolean
      delete?: Prisma.ProductVariantAttachmentWhereInput | boolean
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.ProductVariantAttachmentUpdateToOneWithWhereWithoutMediaInput, Prisma.ProductVariantAttachmentUpdateWithoutMediaInput>, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantAttachmentUncheckedUpdateOneWithoutMediaNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutMediaInput
      upsert?: Prisma.ProductVariantAttachmentUpsertWithoutMediaInput
      disconnect?: Prisma.ProductVariantAttachmentWhereInput | boolean
      delete?: Prisma.ProductVariantAttachmentWhereInput | boolean
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput
      update?: Prisma.XOR<Prisma.XOR<Prisma.ProductVariantAttachmentUpdateToOneWithWhereWithoutMediaInput, Prisma.ProductVariantAttachmentUpdateWithoutMediaInput>, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantAttachmentCreateNestedManyWithoutProductVariantInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput[] | Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantAttachmentCreateManyProductVariantInputEnvelope
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
    };
export type ProductVariantAttachmentUncheckedCreateNestedManyWithoutProductVariantInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput[] | Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantAttachmentCreateManyProductVariantInputEnvelope
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
    };
export type ProductVariantAttachmentUpdateManyWithoutProductVariantNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput[] | Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput[]
      upsert?: Prisma.ProductVariantAttachmentUpsertWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpsertWithWhereUniqueWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantAttachmentCreateManyProductVariantInputEnvelope
      set?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      disconnect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      delete?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      update?: Prisma.ProductVariantAttachmentUpdateWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpdateWithWhereUniqueWithoutProductVariantInput[]
      updateMany?: Prisma.ProductVariantAttachmentUpdateManyWithWhereWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpdateManyWithWhereWithoutProductVariantInput[]
      deleteMany?: Prisma.ProductVariantAttachmentScalarWhereInput | Prisma.ProductVariantAttachmentScalarWhereInput[]
    };
export type ProductVariantAttachmentUncheckedUpdateManyWithoutProductVariantNestedInput = {
      create?: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput> | Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput[] | Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput[]
      connectOrCreate?: Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput | Prisma.ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput[]
      upsert?: Prisma.ProductVariantAttachmentUpsertWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpsertWithWhereUniqueWithoutProductVariantInput[]
      createMany?: Prisma.ProductVariantAttachmentCreateManyProductVariantInputEnvelope
      set?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      disconnect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      delete?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      connect?: Prisma.ProductVariantAttachmentWhereUniqueInput | Prisma.ProductVariantAttachmentWhereUniqueInput[]
      update?: Prisma.ProductVariantAttachmentUpdateWithWhereUniqueWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpdateWithWhereUniqueWithoutProductVariantInput[]
      updateMany?: Prisma.ProductVariantAttachmentUpdateManyWithWhereWithoutProductVariantInput | Prisma.ProductVariantAttachmentUpdateManyWithWhereWithoutProductVariantInput[]
      deleteMany?: Prisma.ProductVariantAttachmentScalarWhereInput | Prisma.ProductVariantAttachmentScalarWhereInput[]
    };
export type ProductVariantAttachmentCreateWithoutMediaInput = {
      id?: string
      productVariant: Prisma.ProductVariantCreateNestedOneWithoutAttachmentsInput
    };
export type ProductVariantAttachmentUncheckedCreateWithoutMediaInput = {
      id?: string
      productVariantId: string
    };
export type ProductVariantAttachmentCreateOrConnectWithoutMediaInput = {
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
      create: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
    };
export type ProductVariantAttachmentUpsertWithoutMediaInput = {
      update: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutMediaInput>
      create: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutMediaInput>
      where?: Prisma.ProductVariantAttachmentWhereInput
    };
export type ProductVariantAttachmentUpdateToOneWithWhereWithoutMediaInput = {
      where?: Prisma.ProductVariantAttachmentWhereInput
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateWithoutMediaInput, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutMediaInput>
    };
export type ProductVariantAttachmentUpdateWithoutMediaInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      productVariant?: Prisma.ProductVariantUpdateOneRequiredWithoutAttachmentsNestedInput
    };
export type ProductVariantAttachmentUncheckedUpdateWithoutMediaInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      productVariantId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentCreateWithoutProductVariantInput = {
      id?: string
      media: Prisma.MediaCreateNestedOneWithoutProductVariantAttachmentInput
    };
export type ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput = {
      id?: string
      mediaId: string
    };
export type ProductVariantAttachmentCreateOrConnectWithoutProductVariantInput = {
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
      create: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput>
    };
export type ProductVariantAttachmentCreateManyProductVariantInputEnvelope = {
      data: Prisma.ProductVariantAttachmentCreateManyProductVariantInput | Prisma.ProductVariantAttachmentCreateManyProductVariantInput[]
      skipDuplicates?: boolean
    };
export type ProductVariantAttachmentUpsertWithWhereUniqueWithoutProductVariantInput = {
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
      update: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutProductVariantInput>
      create: Prisma.XOR<Prisma.ProductVariantAttachmentCreateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedCreateWithoutProductVariantInput>
    };
export type ProductVariantAttachmentUpdateWithWhereUniqueWithoutProductVariantInput = {
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateWithoutProductVariantInput, Prisma.ProductVariantAttachmentUncheckedUpdateWithoutProductVariantInput>
    };
export type ProductVariantAttachmentUpdateManyWithWhereWithoutProductVariantInput = {
      where: Prisma.ProductVariantAttachmentScalarWhereInput
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateManyMutationInput, Prisma.ProductVariantAttachmentUncheckedUpdateManyWithoutProductVariantInput>
    };
export type ProductVariantAttachmentScalarWhereInput = {
      AND?: Prisma.ProductVariantAttachmentScalarWhereInput | Prisma.ProductVariantAttachmentScalarWhereInput[]
      OR?: Prisma.ProductVariantAttachmentScalarWhereInput[]
      NOT?: Prisma.ProductVariantAttachmentScalarWhereInput | Prisma.ProductVariantAttachmentScalarWhereInput[]
      id?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      productVariantId?: Prisma.StringFilter<"ProductVariantAttachment"> | string
      mediaId?: Prisma.StringFilter<"ProductVariantAttachment"> | string
    };
export type ProductVariantAttachmentCreateManyProductVariantInput = {
      id?: string
      mediaId: string
    };
export type ProductVariantAttachmentUpdateWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      media?: Prisma.MediaUpdateOneRequiredWithoutProductVariantAttachmentNestedInput
    };
export type ProductVariantAttachmentUncheckedUpdateWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentUncheckedUpdateManyWithoutProductVariantInput = {
      id?: Prisma.StringFieldUpdateOperationsInput | string
      mediaId?: Prisma.StringFieldUpdateOperationsInput | string
    };
export type ProductVariantAttachmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantAttachment"]>;
export type ProductVariantAttachmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantAttachment"]>;
export type ProductVariantAttachmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
      id?: boolean
      productVariantId?: boolean
      mediaId?: boolean
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    }, ExtArgs["result"]["productVariantAttachment"]>;
export type ProductVariantAttachmentSelectScalar = {
      id?: boolean
      productVariantId?: boolean
      mediaId?: boolean
    };
export type ProductVariantAttachmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productVariantId" | "mediaId", ExtArgs["result"]["productVariantAttachment"]>;
export type ProductVariantAttachmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type ProductVariantAttachmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type ProductVariantAttachmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      productVariant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
      media?: boolean | Prisma.MediaDefaultArgs<ExtArgs>
    };
export type $ProductVariantAttachmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      name: "ProductVariantAttachment"
      objects: {
        productVariant: Prisma.$ProductVariantPayload<ExtArgs>
        media: Prisma.$MediaPayload<ExtArgs>
      }
      scalars: runtime.Types.Extensions.GetPayloadResult<{
        id: string
        productVariantId: string
        mediaId: string
      }, ExtArgs["result"]["productVariantAttachment"]>
      composites: {}
    };
export type ProductVariantAttachmentGetPayload<S extends boolean | null | undefined | ProductVariantAttachmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload, S>;
export type ProductVariantAttachmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = Omit<ProductVariantAttachmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
        select?: ProductVariantAttachmentCountAggregateInputType | true
      };

export interface ProductVariantAttachmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
    [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductVariantAttachment'], meta: { name: 'ProductVariantAttachment' } };
    /**
     * Fields of the ProductVariantAttachment model
     */
    readonly fields: ProductVariantAttachmentFieldRefs;
    /**
     * Find zero or one ProductVariantAttachment that matches the filter.
     * @param {ProductVariantAttachmentFindUniqueArgs} args - Arguments to find a ProductVariantAttachment
     * @example
     * // Get one ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.findUnique({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUnique<T extends ProductVariantAttachmentFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find one ProductVariantAttachment that matches the filter or throw an error with `error.code='P2025'`
     * if no matches were found.
     * @param {ProductVariantAttachmentFindUniqueOrThrowArgs} args - Arguments to find a ProductVariantAttachment
     * @example
     * // Get one ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.findUniqueOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findUniqueOrThrow<T extends ProductVariantAttachmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first ProductVariantAttachment that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentFindFirstArgs} args - Arguments to find a ProductVariantAttachment
     * @example
     * // Get one ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.findFirst({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirst<T extends ProductVariantAttachmentFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>;
    /**
     * Find the first ProductVariantAttachment that matches the filter or
     * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentFindFirstOrThrowArgs} args - Arguments to find a ProductVariantAttachment
     * @example
     * // Get one ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.findFirstOrThrow({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    findFirstOrThrow<T extends ProductVariantAttachmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Find zero or more ProductVariantAttachments that matches the filter.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentFindManyArgs} args - Arguments to filter and select certain fields only.
     * @example
     * // Get all ProductVariantAttachments
     * const productVariantAttachments = await prisma.productVariantAttachment.findMany()
     *
     * // Get first 10 ProductVariantAttachments
     * const productVariantAttachments = await prisma.productVariantAttachment.findMany({ take: 10 })
     *
     * // Only select the `id`
     * const productVariantAttachmentWithIdOnly = await prisma.productVariantAttachment.findMany({ select: { id: true } })
     */
    findMany<T extends ProductVariantAttachmentFindManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>;
    /**
     * Create a ProductVariantAttachment.
     * @param {ProductVariantAttachmentCreateArgs} args - Arguments to create a ProductVariantAttachment.
     * @example
     * // Create one ProductVariantAttachment
     * const ProductVariantAttachment = await prisma.productVariantAttachment.create({
     *   data: {
     *     // ... data to create a ProductVariantAttachment
     *   }
     * })
     */
    create<T extends ProductVariantAttachmentCreateArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentCreateArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Create many ProductVariantAttachments.
     * @param {ProductVariantAttachmentCreateManyArgs} args - Arguments to create many ProductVariantAttachments.
     * @example
     * // Create many ProductVariantAttachments
     * const productVariantAttachment = await prisma.productVariantAttachment.createMany({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     */
    createMany<T extends ProductVariantAttachmentCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Create many ProductVariantAttachments and returns the data saved in the database.
     * @param {ProductVariantAttachmentCreateManyAndReturnArgs} args - Arguments to create many ProductVariantAttachments.
     * @example
     * // Create many ProductVariantAttachments
     * const productVariantAttachment = await prisma.productVariantAttachment.createManyAndReturn({
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Create many ProductVariantAttachments and only return the `id`
     * const productVariantAttachmentWithIdOnly = await prisma.productVariantAttachment.createManyAndReturn({
     *   select: { id: true },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    createManyAndReturn<T extends ProductVariantAttachmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>;
    /**
     * Delete a ProductVariantAttachment.
     * @param {ProductVariantAttachmentDeleteArgs} args - Arguments to delete one ProductVariantAttachment.
     * @example
     * // Delete one ProductVariantAttachment
     * const ProductVariantAttachment = await prisma.productVariantAttachment.delete({
     *   where: {
     *     // ... filter to delete one ProductVariantAttachment
     *   }
     * })
     */
    delete<T extends ProductVariantAttachmentDeleteArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Update one ProductVariantAttachment.
     * @param {ProductVariantAttachmentUpdateArgs} args - Arguments to update one ProductVariantAttachment.
     * @example
     * // Update one ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.update({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    update<T extends ProductVariantAttachmentUpdateArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Delete zero or more ProductVariantAttachments.
     * @param {ProductVariantAttachmentDeleteManyArgs} args - Arguments to filter ProductVariantAttachments to delete.
     * @example
     * // Delete a few ProductVariantAttachments
     * const { count } = await prisma.productVariantAttachment.deleteMany({
     *   where: {
     *     // ... provide filter here
     *   }
     * })
     */
    deleteMany<T extends ProductVariantAttachmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductVariantAttachmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more ProductVariantAttachments.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentUpdateManyArgs} args - Arguments to update one or more rows.
     * @example
     * // Update many ProductVariantAttachments
     * const productVariantAttachment = await prisma.productVariantAttachment.updateMany({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: {
     *     // ... provide data here
     *   }
     * })
     */
    updateMany<T extends ProductVariantAttachmentUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>;
    /**
     * Update zero or more ProductVariantAttachments and returns the data updated in the database.
     * @param {ProductVariantAttachmentUpdateManyAndReturnArgs} args - Arguments to update many ProductVariantAttachments.
     * @example
     * // Update many ProductVariantAttachments
     * const productVariantAttachment = await prisma.productVariantAttachment.updateManyAndReturn({
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     *
     * // Update zero or more ProductVariantAttachments and only return the `id`
     * const productVariantAttachmentWithIdOnly = await prisma.productVariantAttachment.updateManyAndReturn({
     *   select: { id: true },
     *   where: {
     *     // ... provide filter here
     *   },
     *   data: [
     *     // ... provide data here
     *   ]
     * })
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     */
    updateManyAndReturn<T extends ProductVariantAttachmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>;
    /**
     * Create or update one ProductVariantAttachment.
     * @param {ProductVariantAttachmentUpsertArgs} args - Arguments to update or create a ProductVariantAttachment.
     * @example
     * // Update or create a ProductVariantAttachment
     * const productVariantAttachment = await prisma.productVariantAttachment.upsert({
     *   create: {
     *     // ... data to create a ProductVariantAttachment
     *   },
     *   update: {
     *     // ... in case it already exists, update
     *   },
     *   where: {
     *     // ... the filter for the ProductVariantAttachment we want to update
     *   }
     * })
     */
    upsert<T extends ProductVariantAttachmentUpsertArgs>(args: Prisma.SelectSubset<T, ProductVariantAttachmentUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductVariantAttachmentClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantAttachmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>;
    /**
     * Count the number of ProductVariantAttachments.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentCountArgs} args - Arguments to filter ProductVariantAttachments to count.
     * @example
     * // Count the number of ProductVariantAttachments
     * const count = await prisma.productVariantAttachment.count({
     *   where: {
     *     // ... the filter for the ProductVariantAttachments we want to count
     *   }
     * })
     */
    count<T extends ProductVariantAttachmentCountArgs>(args?: Prisma.Subset<T, ProductVariantAttachmentCountArgs>): Prisma.PrismaPromise<
        T extends runtime.Types.Utils.Record<'select', any>
          ? T['select'] extends true
            ? number
            : Prisma.GetScalarType<T['select'], ProductVariantAttachmentCountAggregateOutputType>
          : number
        >;
    /**
     * Allows you to perform aggregations operations on a ProductVariantAttachment.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
     * @example
     * // Ordered by age ascending
     * // Where email contains prisma.io
     * // Limited to the 10 users
     * const aggregations = await prisma.user.aggregate({
     *   _avg: {
     *     age: true,
     *   },
     *   where: {
     *     email: {
     *       contains: "prisma.io",
     *     },
     *   },
     *   orderBy: {
     *     age: "asc",
     *   },
     *   take: 10,
     * })
     */
    aggregate<T extends ProductVariantAttachmentAggregateArgs>(args: Prisma.Subset<T, ProductVariantAttachmentAggregateArgs>): Prisma.PrismaPromise<GetProductVariantAttachmentAggregateType<T>>;
    /**
     * Group by ProductVariantAttachment.
     * Note, that providing `undefined` is treated as the value not being there.
     * Read more here: https://pris.ly/d/null-undefined
     * @param {ProductVariantAttachmentGroupByArgs} args - Group by arguments.
     * @example
     * // Group by city, order by createdAt, get count
     * const result = await prisma.user.groupBy({
     *   by: ['city', 'createdAt'],
     *   orderBy: {
     *     createdAt: true
     *   },
     *   _count: {
     *     _all: true
     *   },
     * })
     */
    groupBy<T extends ProductVariantAttachmentGroupByArgs, HasSelectOrTake extends Prisma.Or<
          Prisma.Extends<'skip', Prisma.Keys<T>>,
          Prisma.Extends<'take', Prisma.Keys<T>>
        >, OrderByArg extends Prisma.True extends HasSelectOrTake
        ? { orderBy: ProductVariantAttachmentGroupByArgs['orderBy'] }
        : { orderBy?: ProductVariantAttachmentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<T['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<T['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
        ? `Error: "by" must not be empty.`
        : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  'Field ',
                  P,
                  ` in "having" needs to be provided in "by"`,
                ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "skip", you also need to provide "orderBy"'
        : ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]>(args: Prisma.SubsetIntersection<T, ProductVariantAttachmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductVariantAttachmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductVariantAttachment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductVariantAttachmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
    readonly [Symbol.toStringTag]: "PrismaPromise";
    productVariant<T extends Prisma.ProductVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductVariantClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>;
    media<T extends Prisma.MediaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MediaDefaultArgs<ExtArgs>>): Prisma.Prisma__MediaClient<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>;
    /**
     * Attaches callbacks for the resolution and/or rejection of the Promise.
     * @param onfulfilled The callback to execute when the Promise is resolved.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of which ever callback is executed.
     */
    then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
    /**
     * Attaches a callback for only the rejection of the Promise.
     * @param onrejected The callback to execute when the Promise is rejected.
     * @returns A Promise for the completion of the callback.
     */
    catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>;
    /**
     * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
     * resolved value cannot be modified from the callback.
     * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
     * @returns A Promise for the completion of the callback.
     */
    finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ProductVariantAttachment model
 */
export interface ProductVariantAttachmentFieldRefs {
    readonly id: Prisma.FieldRef<"ProductVariantAttachment", 'String'>;
    readonly productVariantId: Prisma.FieldRef<"ProductVariantAttachment", 'String'>;
    readonly mediaId: Prisma.FieldRef<"ProductVariantAttachment", 'String'>;
}

// Custom InputTypes
/**
 * ProductVariantAttachment findUnique
 */
export type ProductVariantAttachmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantAttachment to fetch.
       */
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
/**
 * ProductVariantAttachment findUniqueOrThrow
 */
export type ProductVariantAttachmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantAttachment to fetch.
       */
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
/**
 * ProductVariantAttachment findFirst
 */
export type ProductVariantAttachmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantAttachment to fetch.
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantAttachments to fetch.
       */
      orderBy?: Prisma.ProductVariantAttachmentOrderByWithRelationInput | Prisma.ProductVariantAttachmentOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for ProductVariantAttachments.
       */
      cursor?: Prisma.ProductVariantAttachmentWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantAttachments from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantAttachments.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of ProductVariantAttachments.
       */
      distinct?: Prisma.ProductVariantAttachmentScalarFieldEnum | Prisma.ProductVariantAttachmentScalarFieldEnum[]
    };
/**
 * ProductVariantAttachment findFirstOrThrow
 */
export type ProductVariantAttachmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantAttachment to fetch.
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantAttachments to fetch.
       */
      orderBy?: Prisma.ProductVariantAttachmentOrderByWithRelationInput | Prisma.ProductVariantAttachmentOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for searching for ProductVariantAttachments.
       */
      cursor?: Prisma.ProductVariantAttachmentWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantAttachments from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantAttachments.
       */
      skip?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
       * 
       * Filter by unique combinations of ProductVariantAttachments.
       */
      distinct?: Prisma.ProductVariantAttachmentScalarFieldEnum | Prisma.ProductVariantAttachmentScalarFieldEnum[]
    };
/**
 * ProductVariantAttachment findMany
 */
export type ProductVariantAttachmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter, which ProductVariantAttachments to fetch.
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
       * 
       * Determine the order of ProductVariantAttachments to fetch.
       */
      orderBy?: Prisma.ProductVariantAttachmentOrderByWithRelationInput | Prisma.ProductVariantAttachmentOrderByWithRelationInput[]
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
       * 
       * Sets the position for listing ProductVariantAttachments.
       */
      cursor?: Prisma.ProductVariantAttachmentWhereUniqueInput
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Take `±n` ProductVariantAttachments from the position of the cursor.
       */
      take?: number
      /**
       * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
       * 
       * Skip the first `n` ProductVariantAttachments.
       */
      skip?: number
      distinct?: Prisma.ProductVariantAttachmentScalarFieldEnum | Prisma.ProductVariantAttachmentScalarFieldEnum[]
    };
/**
 * ProductVariantAttachment create
 */
export type ProductVariantAttachmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * The data needed to create a ProductVariantAttachment.
       */
      data: Prisma.XOR<Prisma.ProductVariantAttachmentCreateInput, Prisma.ProductVariantAttachmentUncheckedCreateInput>
    };
/**
 * ProductVariantAttachment createMany
 */
export type ProductVariantAttachmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to create many ProductVariantAttachments.
       */
      data: Prisma.ProductVariantAttachmentCreateManyInput | Prisma.ProductVariantAttachmentCreateManyInput[]
      skipDuplicates?: boolean
    };
/**
 * ProductVariantAttachment createManyAndReturn
 */
export type ProductVariantAttachmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelectCreateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * The data used to create many ProductVariantAttachments.
       */
      data: Prisma.ProductVariantAttachmentCreateManyInput | Prisma.ProductVariantAttachmentCreateManyInput[]
      skipDuplicates?: boolean
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentIncludeCreateManyAndReturn<ExtArgs> | null
    };
/**
 * ProductVariantAttachment update
 */
export type ProductVariantAttachmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * The data needed to update a ProductVariantAttachment.
       */
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateInput, Prisma.ProductVariantAttachmentUncheckedUpdateInput>
      /**
       * Choose, which ProductVariantAttachment to update.
       */
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
/**
 * ProductVariantAttachment updateMany
 */
export type ProductVariantAttachmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * The data used to update ProductVariantAttachments.
       */
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateManyMutationInput, Prisma.ProductVariantAttachmentUncheckedUpdateManyInput>
      /**
       * Filter which ProductVariantAttachments to update
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * Limit how many ProductVariantAttachments to update.
       */
      limit?: number
    };
/**
 * ProductVariantAttachment updateManyAndReturn
 */
export type ProductVariantAttachmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelectUpdateManyAndReturn<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * The data used to update ProductVariantAttachments.
       */
      data: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateManyMutationInput, Prisma.ProductVariantAttachmentUncheckedUpdateManyInput>
      /**
       * Filter which ProductVariantAttachments to update
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * Limit how many ProductVariantAttachments to update.
       */
      limit?: number
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentIncludeUpdateManyAndReturn<ExtArgs> | null
    };
/**
 * ProductVariantAttachment upsert
 */
export type ProductVariantAttachmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * The filter to search for the ProductVariantAttachment to update in case it exists.
       */
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
      /**
       * In case the ProductVariantAttachment found by the `where` argument doesn't exist, create a new ProductVariantAttachment with this data.
       */
      create: Prisma.XOR<Prisma.ProductVariantAttachmentCreateInput, Prisma.ProductVariantAttachmentUncheckedCreateInput>
      /**
       * In case the ProductVariantAttachment was found with the provided `where` argument, update it with this data.
       */
      update: Prisma.XOR<Prisma.ProductVariantAttachmentUpdateInput, Prisma.ProductVariantAttachmentUncheckedUpdateInput>
    };
/**
 * ProductVariantAttachment delete
 */
export type ProductVariantAttachmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
      /**
       * Filter which ProductVariantAttachment to delete.
       */
      where: Prisma.ProductVariantAttachmentWhereUniqueInput
    };
/**
 * ProductVariantAttachment deleteMany
 */
export type ProductVariantAttachmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Filter which ProductVariantAttachments to delete
       */
      where?: Prisma.ProductVariantAttachmentWhereInput
      /**
       * Limit how many ProductVariantAttachments to delete.
       */
      limit?: number
    };
/**
 * ProductVariantAttachment without action
 */
export type ProductVariantAttachmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
      /**
       * Select specific fields to fetch from the ProductVariantAttachment
       */
      select?: Prisma.ProductVariantAttachmentSelect<ExtArgs> | null
      /**
       * Omit specific fields from the ProductVariantAttachment
       */
      omit?: Prisma.ProductVariantAttachmentOmit<ExtArgs> | null
      /**
       * Choose, which related nodes to fetch as well
       */
      include?: Prisma.ProductVariantAttachmentInclude<ExtArgs> | null
    };
